'use client';
import { FormEvent,useEffect,useState } from 'react';
import { money } from '../../components/storefront';
type Tenant={tenant_id:string;slug:string;name:string;lifecycle_status:string;subscription:{status:string;plan:string}};
type Plan={id:string;code:string;version:number;name:string;price_cents:string|null;billing_interval:string;status:string;entitlements:Record<string,number|string>};
const fields=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;};
// Administração da plataforma: papel concedido pelo operador, MFA em toda requisição, motivo obrigatório e auditoria.
export default function Platform(){
 const [csrf,setCsrf]=useState(''),[mfa,setMfa]=useState<{enabled:boolean;verified:boolean}|null>(null),[tenants,setTenants]=useState<Tenant[]>([]),[plans,setPlans]=useState<Plan[]>([]),[alerts,setAlerts]=useState<{slug:string;alerts:{code:string}[]}[]>([]),[audit,setAudit]=useState<{action:string;reason:string;admin:string;created_at:string}[]>([]),[detail,setDetail]=useState<unknown>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function api(path:string,method='GET',body?:unknown,token=csrf){const r=await fetch(`/api/${path}`,{method,cache:'no-store',headers:{...(method==='POST'?{'Content-Type':'application/json'}:{}),'X-CSRF-Token':token},body:method==='POST'?JSON.stringify(body||{}):undefined});const d=await r.json();if(!r.ok)throw new Error(typeof d.error==='string'?d.error:d.error?.message||'Acesso negado.');return d;}
 async function load(token=csrf){setTenants(await api('platform/tenants','GET',undefined,token));setPlans(await api('platform/plans','GET',undefined,token));setAlerts(await api('platform/alerts','GET',undefined,token));setAudit(await api('platform/audit','GET',undefined,token));}
 async function act(action:()=>Promise<unknown>,done:string){setBusy(true);setError('');setNotice('');try{await action();await load();setNotice(done);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void fetch('/api/auth/session',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('Entre com a conta de administração.');const s=await r.json();setCsrf(s.csrf);setMfa(s.mfa);if(s.mfa.verified)await load(s.csrf);}).catch(e=>setError(e.message));},[]);
 return <main><header><p className="eyebrow">Plataforma · acesso restrito e auditado</p><h1>Administração da plataforma</h1><a href="/">Voltar</a></header>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}
 {mfa&&!mfa.verified&&<section><h2>Confirme o MFA</h2>{mfa.enabled?<form aria-label="Confirmar MFA" onSubmit={e=>{const b=fields(e);void act(async()=>{await api('auth/mfa/verify','POST',b);setMfa({enabled:true,verified:true});},'MFA confirmado.');}}><label>Código<input name="code" required autoComplete="one-time-code"/></label><button disabled={busy}>Confirmar</button></form>:<p>Ative o MFA no painel da sua conta antes de administrar a plataforma.</p>}</section>}
 {mfa?.verified&&<>
  <section><h2>Lojas</h2><ul>{tenants.map(t=><li key={t.tenant_id}><strong>{t.name}</strong> ({t.slug}) · {t.lifecycle_status} · {t.subscription.plan} · {t.subscription.status}
   <form aria-label={`Ação em ${t.slug}`} className="row" onSubmit={e=>{const b=fields(e),action=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value');void act(async()=>{if(action==='view')setDetail(await api(`platform/tenants/${t.tenant_id}?reason=${encodeURIComponent(b.reason!)}`));else await api(`platform/tenants/${t.tenant_id}/${action}`,'POST',{reason:b.reason});},'Ação registrada na auditoria.');}}><label>Motivo<input name="reason" required minLength={3} maxLength={500}/></label><button name="op" value="view" disabled={busy}>Consultar</button>{t.lifecycle_status==='SUSPENDED'?<button name="op" value="reactivate" disabled={busy}>Reativar</button>:<button name="op" value="suspend" disabled={busy}>Suspender</button>}</form></li>)}</ul>
   {detail!==null&&<details open><summary>Consulta auditada</summary><pre className="prose">{JSON.stringify(detail,null,2)}</pre></details>}</section>
  <section><h2>Alertas por loja</h2>{alerts.length===0?<p>Nenhum.</p>:<ul>{alerts.map(a=><li key={a.slug}>{a.slug}: {a.alerts.map(x=>x.code).join(', ')}</li>)}</ul>}
   <form aria-label="Executar cobrança" onSubmit={e=>{const b=fields(e);void act(()=>api('platform/billing/run','POST',b),'Ciclo de cobrança executado.');}}><label>Motivo<input name="reason" required minLength={3}/></label><button disabled={busy}>Executar ciclo de cobrança agora</button></form></section>
  <section><h2>Planos (versões imutáveis)</h2><ul>{plans.map(p=><li key={p.id}>{p.code} v{p.version} · {p.name} · {p.price_cents?money(p.price_cents):'sem preço'} · {p.billing_interval} · {p.status} · {JSON.stringify(p.entitlements)}
   {p.status!=='RETIRED'&&p.code!=='PILOT'&&<form className="row" aria-label={`Estado ${p.code} v${p.version}`} onSubmit={e=>{const b=fields(e);void act(()=>api(`platform/plans/${p.id}/${p.status==='DRAFT'?'activate':'retire'}`,'POST',b),'Plano atualizado.');}}><label>Motivo<input name="reason" required minLength={3}/></label><button disabled={busy}>{p.status==='DRAFT'?'Ativar':'Aposentar'}</button></form>}</li>)}</ul>
   <form aria-label="Nova versão de plano" onSubmit={e=>{const b=fields(e);void act(()=>api('platform/plans','POST',{code:b.code,name:b.name,billing_interval:'MONTH',price_cents:b.price_cents||null,reason:b.reason,entitlements:{active_products:Number(b.active_products),active_variants:Number(b.active_variants),media_bytes:Number(b.media_mb)*1048576,members:Number(b.members),media_mode:'STRICT'}}),'Versão criada como rascunho.');}}>
    <label>Código<input name="code" required pattern="[A-Z][A-Z0-9_]{1,30}"/></label><label>Nome<input name="name" required/></label><label>Preço mensal em centavos (vazio até decisão D07)<input name="price_cents" pattern="[0-9]*"/></label><label>Produtos ativos<input name="active_products" type="number" min="1" required defaultValue={100}/></label><label>Variações ativas<input name="active_variants" type="number" min="1" required defaultValue={500}/></label><label>Mídia (MB)<input name="media_mb" type="number" min="1" required defaultValue={1024}/></label><label>Equipe (pessoas)<input name="members" type="number" min="1" required defaultValue={2}/></label><label>Motivo<input name="reason" required minLength={3}/></label><button disabled={busy}>Criar rascunho</button></form></section>
  <section><h2>Auditoria</h2><ul>{audit.map((a,i)=><li key={i}>{new Date(a.created_at).toLocaleString('pt-BR')} · {a.admin} · {a.action} · {a.reason}</li>)}</ul></section></>}
 </main>;
}
