'use client';
import { FormEvent,use,useEffect,useState } from 'react';
import { MfaGate } from '../../../../components/mfa-gate';
type Row={id:string;order_id:string|null;order_number:string|null;kind:string;status:string;created_at:string;due_at:string;overdue:boolean;financial_action_required:boolean};
type Ticket={id:string;order_id:string|null;kind:string;status:string;outcome:string|null;resolution:string|null;created_at:string;due_at:string;contact_name:string|null;contact_email:string|null;financial_notified_at:string|null;financial_reference:string|null;messages:{id:string;author:string;body:string;created_at:string}[]};
const fields=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;};
const kinds:Record<string,string>={SUPPORT:'Atendimento',WITHDRAWAL:'Arrependimento',CANCELLATION:'Cancelamento',DATA_ACCESS:'Acesso a dados',DATA_ERASURE:'Eliminação de dados',CONTACT:'Contato geral'};
export default function Support({params}:{params:Promise<{tenantId:string}>}){
 const [mfaCsrf,setMfaCsrf]=useState('');
 const {tenantId}=use(params),[csrf,setCsrf]=useState(''),[list,setList]=useState<Row[]|null>(null),[ticket,setTicket]=useState<Ticket|null>(null),[filter,setFilter]=useState('open'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[owner,setOwner]=useState(false);
 async function api(path:string,method='GET',body?:unknown,token=csrf){const response=await fetch(`/api/tenants/${tenantId}/operations/${path}`,{method,cache:'no-store',headers:{...(method==='POST'?{'Content-Type':'application/json'}:{}),'X-CSRF-Token':token},body:method==='POST'?JSON.stringify(body||{}):undefined});const data=await response.json();if(!response.ok)throw new Error(typeof data.error==='string'?data.error:data.error?.message||'Acesso negado.');return data;}
 async function refresh(token=csrf,f=filter,current=ticket?.id){setList(await api(`support?filter=${f}`,'GET',undefined,token));if(current)setTicket(await api(`support/${current}`,'GET',undefined,token));}
 async function act(action:()=>Promise<unknown>,done:string){setBusy(true);setError('');setNotice('');try{await action();await refresh();setNotice(done);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void fetch('/api/auth/session',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('Entre no painel para continuar.');const s=await r.json();if(s.mfa?.enabled&&!s.mfa.verified){setMfaCsrf(s.csrf);return;}setCsrf(s.csrf);const stores=await fetch('/api/tenants',{cache:'no-store'}).then(r=>r.json());setOwner(stores.some((t:{id:string;role:string})=>t.id===tenantId&&t.role==='OWNER'));const hash=location.hash.slice(1);await refresh(s.csrf,'open',/^[0-9a-f-]{36}$/.test(hash)?hash:undefined);}).catch(e=>setError(e.message));},[tenantId]);
 const t=ticket,financial=t&&t.order_id&&['WITHDRAWAL','CANCELLATION'].includes(t.kind);
 return <main><header><p className="eyebrow">Administração · Atendimento ao consumidor</p><h1>Atendimento</h1><nav className="row"><a href={`/painel/${tenantId}/pedidos`}>Pedidos</a><a href={`/painel/${tenantId}/operacao`}>Operação</a><a href={`/painel/${tenantId}`}>Catálogo</a></nav></header>{error&&<p role="alert" className="error">{error}</p>}{mfaCsrf&&<MfaGate csrf={mfaCsrf}/>}{notice&&<p role="status" className="success">{notice}</p>}
 <section><h2>Protocolos</h2><p>Prazo de resposta: 5 dias (Decreto 7.962/2013). Arrependimento e cancelamento de pedido pago exigem comunicação imediata ao meio de pagamento, registrada aqui.</p><div className="row">{['open','overdue','all'].map(f=><button key={f} disabled={busy||filter===f} onClick={()=>{setFilter(f);void act(()=>refresh(csrf,f),'Lista atualizada.');}}>{f==='open'?'Abertos':f==='overdue'?'Atrasados':'Todos'}</button>)}</div>
  {!list?<p>Carregando…</p>:list.length===0?<p>Nenhum protocolo.</p>:<ul>{list.map(r=><li key={r.id}><button className="link" disabled={busy} onClick={()=>void act(async()=>setTicket(await api(`support/${r.id}`)),'Protocolo carregado.')}>{kinds[r.kind]||r.kind}{r.order_number?` · pedido nº ${r.order_number}`:''}</button> · {r.status} · prazo {new Date(r.due_at).toLocaleDateString('pt-BR')}{r.overdue&&<strong className="error"> · ATRASADO</strong>}{r.financial_action_required&&<strong className="error"> · comunicação financeira pendente</strong>}</li>)}</ul>}</section>
 {t&&<section aria-label={`Protocolo ${t.id}`}><h2>Protocolo {t.id}</h2><p>{kinds[t.kind]} · {t.status} · aberto em {new Date(t.created_at).toLocaleString('pt-BR')} (horário original preservado) · prazo {new Date(t.due_at).toLocaleDateString('pt-BR')}</p>{t.contact_email&&<p>Contato: {t.contact_name} · {t.contact_email}</p>}{t.order_id&&<p><a href={`/painel/${tenantId}/pedidos`}>Ver pedido no painel</a></p>}
  <ul>{t.messages.map(m=><li key={m.id}><small>{m.author==='STAFF'?'Equipe':m.author==='CONSUMER'?'Consumidor':'Sistema'} · {new Date(m.created_at).toLocaleString('pt-BR')}</small><p className="prose">{m.body}</p></li>)}</ul>
  {financial&&<div className="local"><strong>Comunicação ao meio de pagamento</strong>{t.financial_notified_at?<p>Registrada em {new Date(t.financial_notified_at).toLocaleString('pt-BR')} · referência {t.financial_reference}. Isso não confirma devolução: acompanhe o incidente do pedido até a confirmação do gateway.</p>:owner?<form aria-label="Registrar comunicação financeira" onSubmit={e=>{const b=fields(e);void act(()=>api(`support/${t.id}/financial`,'POST',b),'Comunicação registrada.');}}><label>Referência da comunicação feita no Mercado Pago (protocolo, data/hora)<input name="reference" required maxLength={200}/></label><button disabled={busy}>Registrar comunicação</button></form>:<p>Pendente — somente o Dono registra.</p>}</div>}
  {t.status!=='RESOLVED'?<><div className="row"><button disabled={busy} onClick={()=>void act(()=>api(`support/${t.id}/assign`,'POST'),'Protocolo assumido.')}>Assumir</button></div>
   <form aria-label="Responder consumidor" onSubmit={e=>{const b=fields(e),form=e.currentTarget;void act(async()=>{await api(`support/${t.id}/reply`,'POST',b);form.reset();},'Resposta registrada e notificação enfileirada.');}}><label>Resposta<textarea name="body" required maxLength={4000}/></label><button disabled={busy}>Responder</button></form>
   <form aria-label="Concluir protocolo" onSubmit={e=>{const b=fields(e);void act(()=>api(`support/${t.id}/resolve`,'POST',b),'Protocolo concluído.');}}><label>Resultado<select name="outcome"><option value="INFORMED">Informado/atendido</option><option value="ACCEPTED">Aceito (cancelamento/arrependimento)</option><option value="DECLINED">Recusado com justificativa</option><option value="WITHDRAWN_BY_CONSUMER">Desistência do consumidor</option></select></label><label>Registro da resolução (enviado ao consumidor)<textarea name="resolution" required maxLength={2000}/></label><button disabled={busy}>Concluir</button></form></>
   :<p>Resultado: {t.outcome} — {t.resolution}</p>}</section>}
 </main>;
}
