'use client';
import { FormEvent,use,useEffect,useState } from 'react';
import { MfaGate } from '../../../components/mfa-gate';
import type { Product } from '../../../components/storefront';
import { money } from '../../../components/storefront';
type Catalogue={products:Product[];categories:{id:string;name:string}[];locations:{id:string;name:string}[];inventory:{variant_id:string;on_hand:number;reserved:number}[];movements:{id:string;reason:string;delta:number;balance:number}[];media:{id:string;status:string;stored_bytes:string}[]};
type Settings={profile?:{profile:Record<string,unknown>};state?:{draft_revision_id:string;published_revision_id:string};revisions:{id:string;content:Record<string,unknown>}[];shipping:{id:string;name:string;kind:string;price_cents:string}[]};
const fields=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget));};
export default function Panel({params}:{params:Promise<{tenantId:string}>}){
 const [mfaCsrf,setMfaCsrf]=useState('');
 const {tenantId}=use(params),[csrf,setCsrf]=useState(''),[catalogue,setCatalogue]=useState<Catalogue|null>(null),[settings,setSettings]=useState<Settings|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[owner,setOwner]=useState(false);
 async function api(path:string,method='GET',body?:unknown,token=csrf){const response=await fetch(`/api/tenants/${tenantId}/${path}`,{method,cache:'no-store',headers:{...(body?{'Content-Type':'application/json'}:{}),'X-CSRF-Token':token},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(typeof data.error==='string'?data.error:data.error?.message||'Acesso negado.');return data;}
 async function refresh(token=csrf){const c=await api('catalogue','GET',undefined,token),s=await api('storefront','GET',undefined,token);setCatalogue(c);setSettings(s);}
 async function act(action:()=>Promise<unknown>){setBusy(true);setError('');setNotice('');try{await action();await refresh();setNotice('Alteração persistida.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{setCatalogue(null);setSettings(null);void fetch('/api/auth/session',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('Entre no painel para continuar.');const s=await r.json();if(s.mfa?.enabled&&!s.mfa.verified){setMfaCsrf(s.csrf);return;}setCsrf(s.csrf);const stores=await fetch('/api/tenants',{cache:'no-store'}).then(r=>r.json());setOwner(stores.some((t:{id:string;role:string})=>t.id===tenantId&&t.role==='OWNER'));await refresh(s.csrf);}).catch(e=>setError(e.message));},[tenantId]);
 const variants=catalogue?.products.flatMap(p=>p.variants.map(v=>({...v,label:`${p.name} · ${v.sku}`})))||[];
 return <main><header><p className="eyebrow">Administração · Fase 2</p><h1>Catálogo e vitrine</h1><a href="/">Voltar às lojas</a> · <a href={`/preview/${tenantId}`}>Preview autorizado</a> · <a href={`/painel/${tenantId}/pedidos`}>Pedidos e pagamentos</a> · <a href={`/painel/${tenantId}/atendimento`}>Atendimento</a> · <a href={`/painel/${tenantId}/operacao`}>Operação</a></header>{error&&<p role="alert" className="error">{error}</p>}{mfaCsrf&&<MfaGate csrf={mfaCsrf}/>}{notice&&<p role="status" className="success">{notice}</p>}{!catalogue?<p>Carregando dados autorizados…</p>:<>
 <div className="grid"><section><h2>Cadastrar produto simples</h2><form aria-label="Cadastrar produto" onSubmit={e=>{const b=fields(e);if(!b.category_id)delete b.category_id;void act(()=>api('catalogue/products','POST',b));}}><label>Nome<input name="name" required maxLength={200}/></label><label>Slug<input name="slug" pattern="[a-z0-9]+(-[a-z0-9]+)*" required/></label><label>Descrição e cuidados<textarea name="description" maxLength={8000}/></label><label>SKU<input name="sku" required maxLength={80}/></label><label>Preço em centavos (inteiro)<input name="price_cents" pattern="[0-9]+" inputMode="numeric" required/></label><label>Categoria<select name="category_id"><option value="">Sem categoria</option>{catalogue.categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><button disabled={busy}>Cadastrar produto</button></form></section>
 <section><h2>Categorias e locais</h2><form aria-label="Criar categoria" onSubmit={e=>{const b=fields(e);void act(()=>api('catalogue/categories','POST',b));}}><label>Nome da categoria<input name="name" required/></label><label>Slug da categoria<input name="slug" required/></label><button disabled={busy}>Criar categoria</button></form><form aria-label="Criar local" onSubmit={e=>{const b=fields(e);void act(()=>api('catalogue/locations','POST',b));}}><label>Local de estoque<input name="name" required/></label><button disabled={busy}>Criar local</button></form></section>
 <section><h2>Ajustar saldo auditado</h2><form aria-label="Ajustar estoque" onSubmit={e=>{const b=fields(e);void act(()=>api('catalogue/adjustments','POST',{...b,delta:Number(b.delta)}));}}><label>Variação<select name="variant_id" required>{variants.map(v=><option value={v.id} key={v.id}>{v.label}</option>)}</select></label><label>Local<select name="location_id" required>{catalogue.locations.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select></label><label>Delta (entrada positiva, saída negativa)<input name="delta" type="number" required/></label><label>Motivo<input name="reason" required maxLength={500}/></label><button disabled={busy||!catalogue.locations.length||!variants.length}>Registrar ajuste</button></form><ul>{catalogue.movements.slice(0,8).map(m=><li key={m.id}>{m.reason}: {m.delta} → saldo {m.balance}</li>)}</ul></section>
 <section><h2>Mídia privada</h2><p>JPEG, PNG e WebP estático, até 10 MB/40 MP. Máximo 2 uploads por loja em andamento. WebP gerado pelo worker.</p><form aria-label="Enviar imagem" onSubmit={e=>{e.preventDefault();const file=new FormData(e.currentTarget).get('image') as File;void act(async()=>{const response=await fetch(`/api/tenants/${tenantId}/catalogue/media`,{method:'POST',headers:{'Content-Type':'application/octet-stream','X-CSRF-Token':csrf},body:file});if(!response.ok)throw new Error('Upload recusado; confira conteúdo, limites e storage.');});}}><label>Imagem<input name="image" type="file" accept="image/jpeg,image/png,image/webp" required/></label><button disabled={busy}>Enviar imagem</button></form><button disabled={busy} onClick={()=>void act(()=>refresh())}>Atualizar processamento</button><button disabled={busy} onClick={()=>void act(()=>api('catalogue/media/maintenance','POST'))}>Reconciliar mídia e retomar pendências</button><ul>{catalogue.media.map(m=><li key={m.id}><code>{m.id}</code> · {m.status} · {m.stored_bytes} bytes</li>)}</ul></section></div>
 <section><h2>Produtos</h2>{catalogue.products.map(p=><details key={p.id}><summary>{p.name} · {p.status}</summary><p className="prose">{p.description}</p><form aria-label={`Editar ${p.name}`} onSubmit={e=>{const b=fields(e);void act(()=>api(`catalogue/products/${p.id}`,'PATCH',b));}}><label>Nome<input name="name" defaultValue={p.name} required/></label><label>Slug<input name="slug" defaultValue={p.slug} required/></label><label>Descrição<textarea name="description" defaultValue={p.description}/></label><label>Status<select name="status" defaultValue={p.status}><option>DRAFT</option><option>ACTIVE</option><option>ARCHIVED</option></select></label><button disabled={busy}>Salvar produto</button></form>
 <h3>Variações</h3>{p.variants.map(v=><form aria-label={`Preço ${v.sku}`} key={v.id} onSubmit={e=>{const b=fields(e);void act(()=>api(`catalogue/variants/${v.id}`,'PATCH',b));}}><p>{v.sku} · {Object.entries(v.attributes).map(([k,value])=>`${k}: ${value}`).join(', ')||'Padrão'} · {v.active?'ativa':'inativa'} · saldo {v.available}</p><label>Preço em centavos<input name="price_cents" defaultValue={v.price_cents} required pattern="[0-9]+"/></label><button disabled={busy}>Salvar preço</button></form>)}
 <form aria-label={`Nova variação ${p.name}`} onSubmit={e=>{const b=fields(e);void act(async()=>{const attributes=JSON.parse(String(b.attributes));return api(`catalogue/products/${p.id}/variants`,'POST',{sku:b.sku,price_cents:b.price_cents,attributes});});}}><h3>Adicionar variação explícita</h3><p>A primeira desativa a opção padrão, preservando seu histórico.</p><label>SKU da variação<input name="sku" required/></label><label>Preço em centavos<input name="price_cents" required pattern="[0-9]+"/></label><label>Atributos (JSON, exemplo: cor e tamanho)<textarea name="attributes" defaultValue={'{"cor":"Azul","tamanho":"M"}'} required/></label><button disabled={busy}>Adicionar variação</button></form>
 <form aria-label={`Vincular imagem ${p.name}`} onSubmit={e=>{const b=fields(e);void act(()=>api(`catalogue/products/${p.id}/media`,'POST',b));}}><label>Imagem processada<select name="asset_id" required>{catalogue.media.filter(m=>m.status==='READY').map(m=><option value={m.id} key={m.id}>{m.id}</option>)}</select></label><button disabled={busy||!catalogue.media.some(m=>m.status==='READY')}>Vincular imagem</button></form></details>)}</section>
 {owner&&settings&&<><section><h2>Fornecedor e políticas</h2><p>Publicação local sintética exige nome com TESTE. Sem identidade fiscal inventada. Dados reais e políticas dependem de validação antes do piloto.</p><form aria-label="Perfil do fornecedor" onSubmit={e=>{const b=fields(e);void act(()=>api('storefront/profile','POST',{...b,synthetic:b.synthetic==='on'}));}}><label><input name="synthetic" type="checkbox" defaultChecked={settings.profile?.profile.synthetic!==false}/> Perfil sintético TESTE</label>{['name','document','address','email','phone','delivery','risks'].map(key=><label key={key}>{({name:'Nome do fornecedor',document:'CPF/CNPJ (vazio para teste)',address:'Endereço físico de teste',email:'E-mail de contato',phone:'Telefone',delivery:'Entrega e restrições',risks:'Cuidados e riscos'})[key as 'name']}<input name={key} defaultValue={String(settings.profile?.profile[key]||'')} required={key!=='document'&&key!=='risks'}/></label>)}<label>Políticas<textarea name="policies" defaultValue={String(settings.profile?.profile.policies||'')} required/></label><button disabled={busy}>Salvar fornecedor</button></form></section>
 <section><h2>Tema — rascunho e publicação</h2><form aria-label="Salvar tema" key={settings.state?.draft_revision_id||'novo'} onSubmit={e=>{const b=fields(e);void act(()=>api('storefront/draft','POST',{schema_version:1,title:b.title,description:b.description,hero:b.hero,color:b.color,font:b.font,pages:JSON.parse(String(b.pages)),menu:JSON.parse(String(b.menu)),assets:JSON.parse(String(b.assets))}));}}><label>Título<input name="title" required defaultValue={String(settings.revisions[0]?.content.title||'Minha loja TESTE')}/></label><label>Descrição<input name="description" required defaultValue={String(settings.revisions[0]?.content.description||'Vitrine sintética de demonstração')}/></label><label>Mensagem principal<input name="hero" defaultValue={String(settings.revisions[0]?.content.hero||'Escolha seu próximo favorito')}/></label><label>Cor<input name="color" type="color" defaultValue={String(settings.revisions[0]?.content.color||'#245742')}/></label><label>Fonte<select name="font" defaultValue={String(settings.revisions[0]?.content.font||'system')}><option value="system">Sistema</option><option value="serif">Serifada</option></select></label><label>Páginas em texto (JSON)<textarea name="pages" defaultValue={JSON.stringify(settings.revisions[0]?.content.pages||[{slug:'sobre',title:'Sobre a loja TESTE',body:'Esta loja é uma demonstração sintética.'}])}/></label><label>Menu interno (JSON)<textarea name="menu" defaultValue={JSON.stringify(settings.revisions[0]?.content.menu||[{label:'Catálogo',path:'/'},{label:'Sobre',path:'/paginas/sobre'}])}/></label><label>IDs de mídia do tema (JSON)<textarea name="assets" defaultValue={JSON.stringify(settings.revisions[0]?.content.assets||[])}/></label><button disabled={busy}>Salvar rascunho</button></form><p>Rascunho: {settings.state?.draft_revision_id||'nenhum'} · Publicado: {settings.state?.published_revision_id||'nenhum'}</p><button disabled={busy||!settings.state?.draft_revision_id} onClick={()=>void act(()=>api('storefront/publish','POST',{revision_id:settings.state!.draft_revision_id}))}>Publicar vitrine local</button></section>
 <section><h2>Frete local</h2><form aria-label="Criar frete" onSubmit={e=>{const b=fields(e);void act(()=>api('storefront/shipping','POST',{...b,days:Number(b.days),priority:Number(b.priority)}));}}><label>Nome do método<input name="name" required/></label><label>Tipo<select name="kind"><option value="TABLE">Tabela de CEP</option><option value="PICKUP">Retirada</option></select></label><label>CEP inicial<input name="cep_start" defaultValue="01000000" pattern="[0-9]{8}" required/></label><label>CEP final<input name="cep_end" defaultValue="09999999" pattern="[0-9]{8}" required/></label><label>Preço em centavos<input name="price_cents" defaultValue="1500" pattern="[0-9]+" required/></label><label>Dias<input name="days" type="number" defaultValue="3" min="0" required/></label><label>Prioridade (maior vence)<input name="priority" type="number" defaultValue="0" required/></label><button disabled={busy}>Criar método de frete</button></form><ul>{settings.shipping.map(s=><li key={s.id}>{s.name} · {s.kind} · {money(s.price_cents)}</li>)}</ul></section></>}
 </>}</main>;
}
