'use client';
import { FormEvent,use,useEffect,useState } from 'react';
import { MfaGate } from '../../../../components/mfa-gate';
import { CommercialSections } from '../../../../components/commercial';
import { AiDraftSection } from '../../../../components/ai-draft';
type Status={outbox_oldest_seconds:number;inbox_oldest_seconds:number;notifications_pending:number;notifications_failed:number;financial_incidents:number;payment_uncertain:number;support_overdue:number;financial_communication_pending:number;suspended:boolean;sales_paused:boolean;alerts:{code:string;severity:string;value:number}[]};
const fields=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;};
const help:Record<string,string>={FINANCIAL_INCIDENT_OPEN:'Há devolução/excedente/divergência aberta: siga o procedimento de incidente financeiro em Pedidos.',PAYMENT_UNCERTAIN:'Pagamento sem resultado conclusivo: solicite nova consulta; não cobre de novo.',FINANCIAL_COMMUNICATION_PENDING:'Arrependimento/cancelamento de pedido pago sem comunicação registrada ao meio de pagamento.',SUPPORT_OVERDUE:'Protocolos com prazo de 5 dias vencido.',NOTIFICATION_BACKLOG:'E-mails pendentes há mais de 15 min: verifique o provedor.',NOTIFICATION_FAILED:'E-mails falharam após as tentativas: reenvie pelo pedido.',OUTBOX_BACKLOG:'Eventos internos atrasados: verifique worker/Redis.',OUTBOX_FAILED:'Eventos esgotaram tentativas: reprocesse pelo pedido.',INBOX_BACKLOG:'Notificações do gateway não processadas: verifique worker.'};
export default function Operation({params}:{params:Promise<{tenantId:string}>}){
 const [mfaCsrf,setMfaCsrf]=useState('');
 const {tenantId}=use(params),[csrf,setCsrf]=useState(''),[status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[owner,setOwner]=useState(false);
 async function api(path:string,method='GET',body?:unknown,token=csrf,extra:Record<string,string>={}){const response=await fetch(`/api/tenants/${tenantId}/operations/${path}`,{method,cache:'no-store',headers:{...(method==='POST'?{'Content-Type':'application/json'}:{}),'X-CSRF-Token':token,...extra},body:method==='POST'?JSON.stringify(body||{}):undefined});const data=await response.json();if(!response.ok)throw new Error(typeof data.error==='string'?data.error:data.error?.message||'Acesso negado.');return data;}
 async function act(action:()=>Promise<unknown>,done:string){setBusy(true);setError('');setNotice('');try{await action();setStatus(await api('status'));setNotice(done);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void fetch('/api/auth/session',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('Entre no painel para continuar.');const s=await r.json();if(s.mfa?.enabled&&!s.mfa.verified){setMfaCsrf(s.csrf);return;}setCsrf(s.csrf);const stores=await fetch('/api/tenants',{cache:'no-store'}).then(r=>r.json());setOwner(stores.some((t:{id:string;role:string})=>t.id===tenantId&&t.role==='OWNER'));setStatus(await api('status','GET',undefined,s.csrf));}).catch(e=>setError(e.message));},[tenantId]);
 async function exportStore(){const e=await api('exports','POST',{kind:'STORE'});const data=await api(`exports/${e.id}`,'GET',undefined,csrf,{'X-Export-Token':e.token});const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`exportacao-loja-${e.id}.json`;a.click();URL.revokeObjectURL(url);}
 return <main><header><p className="eyebrow">Administração · Operação</p><h1>Operação da loja</h1><nav className="row"><a href={`/painel/${tenantId}/pedidos`}>Pedidos</a><a href={`/painel/${tenantId}/atendimento`}>Atendimento</a><a href={`/painel/${tenantId}`}>Catálogo</a></nav></header>{error&&<p role="alert" className="error">{error}</p>}{mfaCsrf&&<MfaGate csrf={mfaCsrf}/>}{notice&&<p role="status" className="success">{notice}</p>}
 {status&&<><section><h2>Alertas</h2>{status.alerts.length===0?<p className="success">Nenhum alerta ativo.</p>:<ul>{status.alerts.map(a=><li key={a.code}><strong className={a.severity==='critical'?'error':''}>{a.code}</strong> ({a.value}) — {help[a.code]}</li>)}</ul>}
  <p>Pendências financeiras: {status.financial_incidents} · incertas: {status.payment_uncertain} · protocolos atrasados: {status.support_overdue} · e-mails pendentes: {status.notifications_pending} (falhos: {status.notifications_failed})</p></section>
 <section><h2>Vendas</h2><p>Estado: {status.suspended?'SUSPENSA pela plataforma':status.sales_paused?'Novas vendas pausadas':'Recebendo pedidos'}. Pausar bloqueia novas compras; pedidos, pagamentos, devoluções e atendimento existentes continuam.</p>
  {owner&&!status.suspended&&(status.sales_paused?<button disabled={busy} onClick={()=>void act(()=>api('sales/resume','POST',{reason:'Retomada pelo Dono'}),'Vendas retomadas.')}>Retomar vendas</button>:<form aria-label="Pausar vendas" onSubmit={e=>{const b=fields(e);void act(()=>api('sales/pause','POST',b),'Novas vendas pausadas.');}}><label>Motivo<input name="reason" required maxLength={500}/></label><button disabled={busy}>Pausar novas vendas</button></form>)}</section>
 {owner&&<section><h2>Exportação privada</h2><p>Gera arquivo JSON com pedidos, pagamentos e protocolos desta loja. O link interno expira em 15 minutos e exige sessão do Dono.</p><button disabled={busy} onClick={()=>void act(exportStore,'Exportação gerada.')}>Exportar dados da loja</button></section>}{csrf&&<AiDraftSection tenantId={tenantId} csrf={csrf} owner={owner}/>}{owner&&csrf&&<CommercialSections tenantId={tenantId} csrf={csrf}/>}</>}
 </main>;
}
