import { createHmac, hkdfSync, timingSafeEqual } from 'node:crypto';
import { newId, rows, sql, withTenant, type Database, type Transaction } from '@ecommerce/database';
import { PurchaseError, simulationEnabled } from './index.js';
// Planos versionados, assinatura e faturas SaaS (seção 16). Cobrança da plataforma é separada das contas dos lojistas.
export type Entitlements={active_products:number;active_variants:number;media_bytes:number;members:number;media_mode:'TOLERANCE'|'STRICT'};
export type Plan={id:string;code:string;version:number;name:string;price_cents:string|null;billing_interval:'NONE'|'MONTH';entitlements:Entitlements;status:string};
export type Subscription={id:string;tenant_id:string;plan_version_id:string;pending_plan_version_id:string|null;status:'TRIAL'|'ACTIVE'|'PAST_DUE'|'SUSPENDED'|'CANCELLED';provider:string;current_period_start:Date;current_period_end:Date|null;cancel_at_period_end:boolean;grace_until:Date|null};
export const GRACE_DAYS=7;
export const PILOT_PLAN='01920000-0000-7000-8000-000000000001';
export async function plan(tx:Transaction,id:string){const [p]=await rows<Plan>(tx,sql`select id,code,version,name,price_cents::text,billing_interval,entitlements,status from platform.plan_versions where id=${id}`);if(!p)throw new PurchaseError(404,'Plano não encontrado.');return p;}
export async function subscription(tx:Transaction,lock=false){let [s]=await rows<Subscription>(tx,sql`select * from shop.subscriptions ${lock?sql`for update`:sql``}`);
 // Stores created before plans existed fall back to the internal PILOT plan.
 if(!s){await tx.execute(sql`insert into shop.subscriptions(id,tenant_id,plan_version_id,status) values(${newId()},shop.current_tenant(),${PILOT_PLAN},'ACTIVE') on conflict(tenant_id) do nothing`);[s]=await rows<Subscription>(tx,sql`select * from shop.subscriptions ${lock?sql`for update`:sql``}`);}
 return s!;}
export async function entitlements(tx:Transaction){return (await plan(tx,(await subscription(tx)).plan_version_id)).entitlements;}
// Server-side quota check under the tenant row lock, so concurrent writes cannot both pass the last slot.
export async function assertQuota(tx:Transaction,resource:'active_products'|'active_variants'|'members',adding:number){
 await tx.execute(sql`select id from shop.tenants where id=shop.current_tenant() for update`);const limit=(await entitlements(tx))[resource];
 const [u]=await rows<{n:number}>(tx,resource==='active_products'?sql`select count(*)::int as n from shop.products where status='ACTIVE'`:resource==='active_variants'?sql`select count(*)::int as n from shop.product_variants v join shop.products p on (p.tenant_id,p.id)=(v.tenant_id,v.product_id) where v.active and p.status='ACTIVE'`:sql`select (select count(*) from shop.tenant_memberships where status='ACTIVE')::int+(select count(*) from shop.invitations where consumed_at is null and expires_at>now())::int as n`);
 if(u!.n+adding>limit)throw new PurchaseError(409,`Limite do plano atingido (${resource}: ${u!.n}/${limit}). Dados existentes são preservados; ajuste o plano ou reduza o uso.`);}
async function audit(tx:Transaction,s:Subscription,event:string,actor:string){const [current]=await rows<Subscription>(tx,sql`select * from shop.subscriptions where id=${s.id}`);const pick=(x:Subscription)=>({status:x.status,plan:x.plan_version_id,pending:x.pending_plan_version_id,period_end:x.current_period_end,cancel:x.cancel_at_period_end});
 await tx.execute(sql`insert into shop.subscription_events(id,tenant_id,subscription_id,event,previous,current,actor) values(${newId()},${s.tenant_id},${s.id},${event},${JSON.stringify(pick(s))}::jsonb,${JSON.stringify(pick(current!))}::jsonb,${actor})`);}
const addMonth=(d:Date)=>{const n=new Date(d);n.setUTCMonth(n.getUTCMonth()+1);return n;};
async function issue(tx:Transaction,s:Subscription,p:Plan,start:Date,end:Date){await tx.execute(sql`insert into shop.saas_invoices(id,tenant_id,subscription_id,plan_version_id,period_start,period_end,amount_cents,due_at) values(${newId()},${s.tenant_id},${s.id},${p.id},${start},${end},${p.price_cents},${start}) on conflict(tenant_id,subscription_id,period_start) do nothing`);}
// Upgrade/downgrade take effect next cycle (no proration). Leaving the free PILOT starts the first paid period now.
export async function changePlan(tx:Transaction,planVersionId:string,actor:string,now=new Date()){const s=await subscription(tx,true),current=await plan(tx,s.plan_version_id),target=await plan(tx,planVersionId);
 if(target.status!=='ACTIVE')throw new PurchaseError(409,'Plano não disponível para contratação.');if(target.id===s.plan_version_id&&!s.pending_plan_version_id)return s;
 if(target.code==='PILOT')throw new PurchaseError(409,'O plano PILOT é atribuído somente pela plataforma.');
 // No recurring-billing provider is homologated (D07): paid plans exist only where the simulator is allowed.
 if(target.billing_interval==='MONTH'&&!simulationEnabled())throw new PurchaseError(409,'Provedor de cobrança recorrente não homologado; contratação de plano pago indisponível.');
 if(current.billing_interval==='NONE'||s.status==='CANCELLED'){const end=addMonth(now);await tx.execute(sql`update shop.subscriptions set plan_version_id=${target.id},pending_plan_version_id=null,status='ACTIVE',provider=${simulationEnabled()?'SIMULATED':'NONE'},current_period_start=${now},current_period_end=${end},cancel_at_period_end=false,grace_until=null,updated_at=now() where id=${s.id}`);const after=await subscription(tx);await issue(tx,after,target,now,end);await audit(tx,s,'PLAN_STARTED',actor);}
 else{await tx.execute(sql`update shop.subscriptions set pending_plan_version_id=${target.id===s.plan_version_id?null:target.id},cancel_at_period_end=false,updated_at=now() where id=${s.id}`);await audit(tx,s,'PLAN_CHANGE_SCHEDULED',actor);}
 return subscription(tx);}
export async function cancelAtPeriodEnd(tx:Transaction,actor:string){const s=await subscription(tx,true);if(!s.current_period_end)throw new PurchaseError(409,'Plano sem cobrança recorrente.');await tx.execute(sql`update shop.subscriptions set cancel_at_period_end=true,pending_plan_version_id=null,updated_at=now() where id=${s.id}`);await audit(tx,s,'CANCEL_REQUESTED',actor);return subscription(tx);}
export async function assignPlan(tx:Transaction,planVersionId:string,actor:string){const s=await subscription(tx,true),p=await plan(tx,planVersionId);if(p.status!=='ACTIVE')throw new PurchaseError(409,'Plano inativo.');if(p.billing_interval!=='NONE')return changePlan(tx,planVersionId,actor);
 await tx.execute(sql`update shop.subscriptions set plan_version_id=${p.id},pending_plan_version_id=null,status='ACTIVE',current_period_end=null,cancel_at_period_end=false,grace_until=null,updated_at=now() where id=${s.id}`);await audit(tx,s,'PLAN_ASSIGNED',actor);return subscription(tx);}
// ---- Provedor de cobrança recorrente. Nenhum homologado (D07): o simulador vive no banco e só existe em development/test.
export type ChargeStatus='PENDING'|'PAID'|'FAILED';
export interface BillingProvider {readonly name:string;charge(tenant:string,invoiceId:string,amountCents:string):Promise<void>;status(tenant:string,invoiceId:string):Promise<ChargeStatus|null>}
export class SimulatedBillingProvider implements BillingProvider {readonly name='SIMULATED';private db:Database;constructor(db:Database){this.db=db;}
 async charge(tenant:string,invoiceId:string,amountCents:string){if(!simulationEnabled())throw new Error('Billing simulator disabled');await withTenant(this.db,tenant,null,tx=>tx.execute(sql`insert into shop.simulated_saas_charges(id,tenant_id,invoice_id,amount_cents) values(${newId()},${tenant},${invoiceId},${amountCents}) on conflict(tenant_id,invoice_id) do update set status=case when shop.simulated_saas_charges.status='FAILED' then 'PENDING' else shop.simulated_saas_charges.status end`));}
 async status(tenant:string,invoiceId:string){if(!simulationEnabled())throw new Error('Billing simulator disabled');const [c]=await withTenant(this.db,tenant,null,tx=>rows<{status:ChargeStatus}>(tx,sql`select status from shop.simulated_saas_charges where invoice_id=${invoiceId}`));return c?.status??null;}}
const billingKey=()=>Buffer.from(hkdfSync('sha256',Buffer.from(process.env.PAYMENT_ENCRYPTION_KEY||'','hex'),Buffer.alloc(0),'saas-billing-simulator',32));
export const billingSignature=(tenant:string,eventId:string,invoiceId:string)=>createHmac('sha256',billingKey()).update(`${tenant}:${eventId}:${invoiceId}`).digest('hex');
// Provider events are deduplicated and only schedule reconciliation; the charge status is always re-read from the provider.
export async function receiveBillingEvent(database:Database,tenant:string,eventId:string,invoiceId:string,signature:string){if(!simulationEnabled())throw new PurchaseError(404,'Provedor não habilitado.');
 const expected=Buffer.from(billingSignature(tenant,eventId,invoiceId),'hex');if(!/^[a-f0-9]{64}$/.test(signature)||!timingSafeEqual(expected,Buffer.from(signature,'hex')))throw new PurchaseError(401,'Assinatura inválida.');
 return withTenant(database,tenant,null,async tx=>{const [inv]=await rows(tx,sql`select id from shop.saas_invoices where id=${invoiceId}`);if(!inv)throw new PurchaseError(404,'Fatura desconhecida.');const r=await tx.execute(sql`insert into shop.saas_billing_inbox(id,tenant_id,provider,event_id,invoice_id) values(${newId()},${tenant},'SIMULATED',${eventId},${invoiceId}) on conflict(provider,event_id) do nothing`);return {received:true,duplicate:!r.rowCount};});}
export async function billingCycle(database:Database,tenant:string,provider:BillingProvider|null,now=new Date()){
 // 1. Period rollover and delinquency transitions (local, short transaction).
 const due=await withTenant(database,tenant,null,async tx=>{const s=await subscription(tx,true);
  if(s.current_period_end&&new Date(s.current_period_end)<=now&&s.status!=='CANCELLED'){
   if(s.cancel_at_period_end){await tx.execute(sql`update shop.subscriptions set status='CANCELLED',updated_at=now() where id=${s.id}`);await audit(tx,s,'CANCELLED_AT_PERIOD_END','SYSTEM');}
   else{const next=await plan(tx,s.pending_plan_version_id??s.plan_version_id),start=new Date(s.current_period_end),end=addMonth(start);await tx.execute(sql`update shop.subscriptions set plan_version_id=${next.id},pending_plan_version_id=null,current_period_start=${start},current_period_end=${end},updated_at=now() where id=${s.id}`);const after=await subscription(tx);if(next.billing_interval==='MONTH')await issue(tx,after,next,start,end);await audit(tx,s,'PERIOD_RENEWED','SYSTEM');}}
  return rows<{id:string;amount_cents:string;charge_requested_at:Date|null}>(tx,sql`select id,amount_cents::text,charge_requested_at from shop.saas_invoices where status='OPEN' order by period_start`);});
 // 2. Charge requests and status reads happen outside transactions; the provider is idempotent per invoice.
 for(const inv of due){if(!provider)break;if(!inv.charge_requested_at){await provider.charge(tenant,inv.id,inv.amount_cents);await withTenant(database,tenant,null,tx=>tx.execute(sql`update shop.saas_invoices set charge_requested_at=now(),provider_ref=${`${provider.name}:${inv.id}`} where id=${inv.id}`));}
  const status=await provider.status(tenant,inv.id);
  await withTenant(database,tenant,null,async tx=>{if(status==='PAID'){const s=await subscription(tx,true);await tx.execute(sql`update shop.saas_invoices set status='PAID',paid_at=now() where id=${inv.id} and status='OPEN'`);const [open]=await rows(tx,sql`select id from shop.saas_invoices where status='OPEN' and due_at<${now} limit 1`);if(!open&&['PAST_DUE','SUSPENDED'].includes(s.status)){await tx.execute(sql`update shop.subscriptions set status='ACTIVE',grace_until=null,updated_at=now() where id=${s.id}`);await audit(tx,s,'PAYMENT_RECOVERED','SYSTEM');}}
   else if(status==='FAILED')await tx.execute(sql`update shop.saas_invoices set charge_requested_at=null where id=${inv.id} and charge_requested_at<now()-interval '1 day'`);
   await tx.execute(sql`update shop.saas_billing_inbox set processed_at=now() where invoice_id=${inv.id} and processed_at is null`);});}
 // 3. Overdue: PAST_DUE with a 7-day grace, then SUSPENDED. Suspension blocks only new sales (assertSalesOpen); orders, refunds, export and billing continue.
 return withTenant(database,tenant,null,async tx=>{const s=await subscription(tx,true);const [overdue]=await rows<{due_at:Date}>(tx,sql`select due_at from shop.saas_invoices where status='OPEN' and due_at<${now} order by due_at limit 1`);
  if(overdue&&s.status==='ACTIVE'){await tx.execute(sql`update shop.subscriptions set status='PAST_DUE',grace_until=${new Date(new Date(overdue.due_at).getTime()+GRACE_DAYS*86400000)},updated_at=now() where id=${s.id}`);await audit(tx,s,'PAST_DUE','SYSTEM');}
  else if(overdue&&s.status==='PAST_DUE'&&s.grace_until&&new Date(s.grace_until)<=now){await tx.execute(sql`update shop.subscriptions set status='SUSPENDED',updated_at=now() where id=${s.id}`);await audit(tx,s,'SUSPENDED_FOR_NON_PAYMENT','SYSTEM');}
  return subscription(tx);});}
export async function billingView(tx:Transaction){const s=await subscription(tx);return {subscription:s,plan:await plan(tx,s.plan_version_id),pending_plan:s.pending_plan_version_id?await plan(tx,s.pending_plan_version_id):null,invoices:await rows(tx,sql`select id,period_start,period_end,amount_cents::text,status,due_at,paid_at from shop.saas_invoices order by period_start desc limit 24`),usage:(await rows(tx,sql`select (select count(*) from shop.products where status='ACTIVE')::int as active_products,(select count(*) from shop.product_variants v join shop.products p on (p.tenant_id,p.id)=(v.tenant_id,v.product_id) where v.active and p.status='ACTIVE')::int as active_variants,(select count(*) from shop.tenant_memberships where status='ACTIVE')::int as members,coalesce((select stored_bytes+reserved_bytes from shop.media_usage),0)::text as media_bytes`))[0],events:await rows(tx,sql`select event,current,actor,created_at from shop.subscription_events order by created_at desc limit 20`)};}
export async function activePlans(tx:Transaction){return rows<Plan>(tx,sql`select id,code,version,name,price_cents::text,billing_interval,entitlements,status from platform.plan_versions where status='ACTIVE' order by code,version`);}
