import { createHash, createHmac, randomBytes, createCipheriv, createDecipheriv, timingSafeEqual } from 'node:crypto';
import { newId, rows, sql, withTenant, type Database, type Transaction } from '@ecommerce/database';
import { notify } from './notifications.js';
export * from './notifications.js';
// Suspension or a sales pause blocks new charges; existing orders, payments and refunds keep being processed.
export async function assertSalesOpen(tx:Transaction){const [t]=await rows<{lifecycle_status:string;sales_paused_at:Date|null;subscription:string|null}>(tx,sql`select t.lifecycle_status,t.sales_paused_at,(select status from shop.subscriptions) as subscription from shop.tenants t where t.id=shop.current_tenant()`);if(!t||t.lifecycle_status!=='ACTIVE'||t.sales_paused_at||['SUSPENDED','CANCELLED'].includes(t.subscription??''))throw new PurchaseError(409,'Novas compras estão suspensas nesta loja. Pedidos existentes continuam atendidos.');}
export const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
export class PurchaseError extends Error { constructor(public status:number,message:string){super(message);} }
export function simulationEnabled(){return ['development','test'].includes(process.env.APP_ENV||'')&&process.env.PAYMENT_SIMULATION==='true';}
export function requireSimulation(){if(!simulationEnabled())throw new PurchaseError(503,'Pagamentos reais não homologados; simulação desabilitada.');}
export function encrypt(value:string,aad:string){const key=Buffer.from(process.env.PAYMENT_ENCRYPTION_KEY||'','hex');if(key.length!==32)throw new Error('Payment encryption key missing');const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv);cipher.setAAD(Buffer.from(aad));const body=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return [iv,cipher.getAuthTag(),body].map(b=>b.toString('base64url')).join('.');}
export function decrypt(value:string,aad:string){const [iv,tag,body]=value.split('.').map(v=>Buffer.from(v,'base64url'));const cipher=createDecipheriv('aes-256-gcm',Buffer.from(process.env.PAYMENT_ENCRYPTION_KEY||'','hex'),iv!);cipher.setAAD(Buffer.from(aad));cipher.setAuthTag(tag!);return Buffer.concat([cipher.update(body!),cipher.final()]).toString('utf8');}
export type Item={variant_id:string;quantity:number;price_cents:string;name:string;sku:string;attributes:Record<string,string>};
export type Order={id:string;tenant_id:string;number:string;cart_id:string;cart_version:string;order_status:string;payment_status:string;fulfillment_status:string;dispute_status:string;total_cents:string;principal_id:string|null;reserved_at:Date;reservation_expires_at:Date;cancel_requested_at:Date|null;version:string};
export async function order(tx:Transaction,id:string,lock=false){const [o]=await rows<Order>(tx,sql`select *,number::text,cart_version::text,total_cents::text,subtotal_cents::text,shipping_cents::text,version::text from shop.orders where id=${id} ${lock?sql`for update`:sql``}`);if(!o)throw new PurchaseError(404,'Pedido não autorizado.');return o;}
export async function view(tx:Transaction,id:string){const o=await order(tx,id);return {...o,simulation:true,items:await rows(tx,sql`select variant_id,quantity,price_cents::text,snapshot from shop.order_items where order_id=${id} order by id`),attempts:await rows(tx,sql`select a.id,a.method,a.status,a.external_id,a.created_at,ac.provider,ac.environment from shop.payment_attempts a join shop.payment_accounts ac on (ac.tenant_id,ac.id)=(a.tenant_id,a.account_id) where a.order_id=${id} order by a.created_at`),transactions:await rows(tx,sql`select t.id,t.external_id,t.received_cents::text,t.currency,t.classification,t.approved_at,coalesce((select sum(amount_cents)::text from shop.payment_refunds r where r.transaction_id=t.id),'0') as refunded_cents from shop.payment_transactions t where t.order_id=${id} order by t.created_at`),incidents:await rows(tx,sql`select id,code,status,due_cents::text,note,created_at from shop.order_incidents where order_id=${id} order by created_at`),protocols:await rows(tx,sql`select id,kind,message,status,outcome,created_at,due_at,resolved_at from shop.consumer_requests where order_id=${id} order by created_at`),refund_requests:await rows(tx,sql`select id,transaction_id,amount_cents::text,status,provider_refund_id,failure_reason,reason,created_at from shop.refund_requests where order_id=${id} order by created_at`),shipment:(await rows(tx,sql`select kind,carrier,tracking_code,ready_at,shipped_at,delivered_at,returned_at from shop.shipments where order_id=${id}`))[0]??null,address_corrections:await rows(tx,sql`select address,reason,created_at from shop.order_address_corrections where order_id=${id} order by created_at`),outbox_failures:Number((await rows<{n:number}>(tx,sql`select count(*)::int as n from shop.purchase_outbox where aggregate_id=${id} and executed_at is null and failures>0`))[0]!.n),history:await rows(tx,sql`select event,previous,current,reason,created_at from shop.order_history where order_id=${id} order by created_at`)};}
const dimensions=(o:Order)=>({order_status:o.order_status,payment_status:o.payment_status,fulfillment_status:o.fulfillment_status,dispute_status:o.dispute_status,principal_id:o.principal_id});
export async function event(tx:Transaction,tenant:string,previous:Order,type:string,reason:string,member:string|null=null){const current=await order(tx,previous.id);await tx.execute(sql`insert into shop.order_history(id,tenant_id,order_id,event,previous,current,actor_membership_id,reason) values(${newId()},${tenant},${previous.id},${type},${JSON.stringify(dimensions(previous))}::jsonb,${JSON.stringify(dimensions(current))}::jsonb,${member},${reason})`);const [v]=await rows<{version:string}>(tx,sql`update shop.orders set version=version+1 where id=${previous.id} returning version::text`);await tx.execute(sql`insert into shop.purchase_outbox(id,tenant_id,aggregate_id,aggregate_version,type) values(${newId()},${tenant},${previous.id},${v!.version},${type})`);}
export async function incident(tx:Transaction,tenant:string,orderId:string,code:string,key:string,transaction:string|null=null,due='0'){await tx.execute(sql`insert into shop.order_incidents(id,tenant_id,order_id,transaction_id,code,operation_key,due_cents) values(${newId()},${tenant},${orderId},${transaction},${code},${key},${due}) on conflict(tenant_id,operation_key) do nothing`);}
type Balance={id:string;variant_id:string;on_hand:number;reserved:number};
async function balances(tx:Transaction,items:Item[]){return rows<Balance>(tx,sql`select id,variant_id,on_hand,reserved from shop.inventory_items where variant_id in (${sql.join(items.map(i=>sql`${i.variant_id}`),sql`,`)}) order by id for update`);}
export async function allocate(tx:Transaction,tenant:string,orderId:string,items:Item[],consume=false){
 const inventory=await balances(tx,items),plan:{item:Balance;quantity:number}[]=[];
 for(const line of items){let left=line.quantity;for(const item of inventory.filter(i=>i.variant_id===line.variant_id)){const quantity=Math.min(left,item.on_hand-item.reserved);if(quantity){plan.push({item,quantity});left-=quantity;}if(!left)break;}if(left)return false;}
 const [g]=await rows<{value:number}>(tx,sql`select coalesce(max(generation),0)+1 as value from shop.inventory_reservations where order_id=${orderId}`);
 for(const {item,quantity} of plan){const reservation=newId();await tx.execute(sql`insert into shop.inventory_reservations(id,tenant_id,order_id,item_id,quantity,status,generation,ended_at) values(${reservation},${tenant},${orderId},${item.id},${quantity},${consume?'CONSUMED':'ACTIVE'},${g!.value},${consume?new Date():null})`);await tx.execute(sql`update shop.inventory_items set on_hand=on_hand-${consume?quantity:0},reserved=reserved+${consume?0:quantity} where id=${item.id}`);await movement(tx,tenant,item.id,reservation,consume?-quantity:0,consume?0:quantity,consume?'REALLOCATE_CONSUME':'RESERVE');}
 return true;
}
async function movement(tx:Transaction,tenant:string,item:string,reservation:string,delta:number,reserved:number,reason:string){await tx.execute(sql`insert into shop.inventory_movements(id,tenant_id,item_id,actor_kind,delta,reserved_delta,balance,reason,reservation_id,operation_key) select ${newId()},${tenant},id,'SYSTEM',${delta},${reserved},on_hand,${reason},${reservation},${reservation+'-'+reason} from shop.inventory_items where id=${item}`);}
export async function endReservations(tx:Transaction,tenant:string,orderId:string,consume:boolean){
 const active=await rows<{id:string;item_id:string;quantity:number}>(tx,sql`select id,item_id,quantity from shop.inventory_reservations where order_id=${orderId} and status='ACTIVE' order by item_id for update`);
 for(const r of active){await tx.execute(sql`select id from shop.inventory_items where id=${r.item_id} for update`);await tx.execute(sql`update shop.inventory_items set on_hand=on_hand-${consume?r.quantity:0},reserved=reserved-${r.quantity} where id=${r.item_id}`);await tx.execute(sql`update shop.inventory_reservations set status=${consume?'CONSUMED':'RELEASED'},ended_at=now() where id=${r.id} and status='ACTIVE'`);await movement(tx,tenant,r.item_id,r.id,consume?-r.quantity:0,-r.quantity,consume?'CONSUME':'RELEASE');}
 return active.length>0;
}
export async function checkoutExisting(tx:Transaction,cart:{id:string;version:string},key:string,fingerprint:string){const [request]=await rows<{order_id:string;fingerprint:string}>(tx,sql`select order_id,fingerprint from shop.checkout_requests where cart_id=${cart.id} and operation_key=${key}`);if(request){if(request.fingerprint!==fingerprint)throw new PurchaseError(409,'Chave reutilizada com conteúdo diferente.');return request.order_id;}const [converted]=await rows<{id:string}>(tx,sql`select id from shop.orders where cart_id=${cart.id} and cart_version=${cart.version}`);return converted?.id;}
export async function createCheckout(tx:Transaction,tenant:string,cart:{id:string;version:string},input:{key:string;fingerprint:string;items:Item[];subtotal:string;shipping:string;address:unknown;buyer:unknown;supplier:unknown;shippingSnapshot:unknown;method:'PIX'|'CARD'}){
 await assertSalesOpen(tx);const [account]=await rows<{id:string}>(tx,sql`select id from shop.payment_accounts where provider='SIMULATED' and environment='SIMULATED' and status='CONNECTED' for share`);if(!account)throw new PurchaseError(409,'O Dono precisa conectar a conta SIMULADA. Métodos reais desabilitados.');
 const [counter]=await rows<{value:string}>(tx,sql`insert into shop.order_counters(id,tenant_id,value) values(${newId()},${tenant},1) on conflict(tenant_id) do update set value=shop.order_counters.value+1 returning value::text`);
 const id=newId(),total=(BigInt(input.subtotal)+BigInt(input.shipping)).toString();
 await tx.execute(sql`insert into shop.orders(id,tenant_id,cart_id,cart_version,number,currency,subtotal_cents,shipping_cents,total_cents,buyer,address,supplier,shipping) values(${id},${tenant},${cart.id},${cart.version},${counter!.value},'BRL',${input.subtotal},${input.shipping},${total},${JSON.stringify(input.buyer)}::jsonb,${JSON.stringify(input.address)}::jsonb,${JSON.stringify(input.supplier)}::jsonb,${JSON.stringify(input.shippingSnapshot)}::jsonb)`);
 for(const i of input.items)await tx.execute(sql`insert into shop.order_items(id,tenant_id,order_id,variant_id,quantity,price_cents,snapshot) values(${newId()},${tenant},${id},${i.variant_id},${i.quantity},${i.price_cents},${JSON.stringify(i)}::jsonb)`);
 if(!await allocate(tx,tenant,id,input.items))throw new PurchaseError(409,'Saldo indisponível; nenhum pedido ou reserva parcial foi criado.');
 const attempt=newId();await tx.execute(sql`insert into shop.payment_attempts(id,tenant_id,order_id,account_id,method,operation_key,expected_cents,currency) values(${attempt},${tenant},${id},${account.id},${input.method},${attempt},${total},'BRL')`);
 await tx.execute(sql`insert into shop.checkout_requests(id,tenant_id,cart_id,operation_key,fingerprint,order_id) values(${newId()},${tenant},${cart.id},${input.key},${input.fingerprint},${id})`);
 await event(tx,tenant,await order(tx,id),'CHECKOUT_CREATED','Intenção confirmada, snapshots e reserva integral.');await notify(tx,tenant,'ORDER_RECEIVED',`order-received-${id}`,{orderId:id});return id;
}
export type PaymentFact={id:string;reference:string;seller_id:string;environment:string;status:string;amount_cents:string;currency:string;approved_at:Date|null;refunds:{id:string;amount_cents:string;confirmed_at:string;key?:string}[];dispute:{id:string;status:'OPEN'|'WON'|'LOST';financial_loss:boolean}|null};
export type Attempt={id:string;order_id:string;account_id:string;method:string;status:string;operation_key:string;expected_cents:string;currency:string;external_id:string|null;provider:string;environment:string;seller_id:string;credentials_cipher:string|null};
export async function attemptData(tx:Transaction,id:string){const [a]=await rows<Attempt>(tx,sql`select a.*,a.expected_cents::text,c.provider,c.environment,c.seller_id,c.credentials_cipher from shop.payment_attempts a join shop.payment_accounts c on (c.tenant_id,c.id)=(a.tenant_id,a.account_id) where a.id=${id}`);if(!a)throw new PurchaseError(404,'Tentativa não encontrada.');return a;}
export class ProviderRejected extends Error {}
export class ProviderUncertain extends Error {}
export interface Gateway { refund?(tenant:string,a:Attempt,paymentId:string,amountCents:string,key:string):Promise<{id:string}>; create(tenant:string,a:Attempt):Promise<PaymentFact>; search(tenant:string,a:Attempt):Promise<PaymentFact[]>; get(tenant:string,a:Attempt,externalId:string):Promise<PaymentFact>; }
// Load rehearsals inject provider latency/errors; only effective where the simulator itself is allowed.
async function providerConditions(){const latency=Number(process.env.SIMULATED_GATEWAY_LATENCY_MS||0),rate=Number(process.env.SIMULATED_GATEWAY_FAILURE_RATE||0);if(latency>0)await new Promise(r=>setTimeout(r,latency));if(rate>0&&Math.random()<rate)throw new Error('SIMULATED_PROVIDER_ERROR');}
export class SimulatedGateway implements Gateway {
 constructor(private database:Database,private loseCreateResponse=false){}
 async create(tenant:string,a:Attempt){requireSimulation();await providerConditions();const fact=await withTenant(this.database,tenant,null,async tx=>{const [account]=await rows(tx,sql`select id from shop.payment_accounts where id=${a.account_id} and status='CONNECTED'`);if(!account)throw new Error('Account revoked');const [f]=await rows<PaymentFact>(tx,sql`insert into shop.simulated_payments(id,tenant_id,account_id,reference,operation_key,amount_cents,seller_id) values(${newId()},${tenant},${a.account_id},${a.id},${a.operation_key},${a.expected_cents},${a.seller_id}) on conflict(tenant_id,operation_key) do update set operation_key=excluded.operation_key returning *,amount_cents::text`);return f!;});if(this.loseCreateResponse)throw new Error('SIMULATED_RESPONSE_LOST');return fact;}
 async search(tenant:string,a:Attempt){requireSimulation();await providerConditions();return withTenant(this.database,tenant,null,async tx=>{await tx.execute(sql`update shop.simulated_payments set status='EXPIRED',revision=revision+1 where reference=${a.id} and status='PENDING' and expires_at<=now()`);return rows<PaymentFact>(tx,sql`select *,amount_cents::text from shop.simulated_payments where account_id=${a.account_id} and reference=${a.id} order by created_at`);});}
 // Refund at the provider: idempotent per key, limited to the remaining balance; test modes reproduce rejection and lost responses.
 async refund(tenant:string,a:Attempt,paymentId:string,amountCents:string,key:string){requireSimulation();await providerConditions();
  const result=await withTenant(this.database,tenant,null,async tx=>{const [p]=await rows<{amount_cents:string;refunds:{id:string;amount_cents:string;key?:string}[];refund_mode:string}>(tx,sql`select amount_cents::text,refunds,refund_mode from shop.simulated_payments where id=${paymentId} and account_id=${a.account_id} for update`);if(!p)throw new ProviderRejected('PAYMENT_NOT_FOUND');
   const existing=p.refunds.find(r=>r.key===key);if(existing)return {id:existing.id,lost:false};if(p.refund_mode==='INSUFFICIENT_BALANCE')throw new ProviderRejected('INSUFFICIENT_BALANCE');
   const refunded=p.refunds.reduce((sum,r)=>sum+BigInt(r.amount_cents),0n);if(refunded+BigInt(amountCents)>BigInt(p.amount_cents))throw new ProviderRejected('AMOUNT_EXCEEDS_BALANCE');
   const refund={id:newId(),key,amount_cents:amountCents,confirmed_at:new Date().toISOString()};await tx.execute(sql`update shop.simulated_payments set refunds=refunds||${JSON.stringify([refund])}::jsonb,status=case when ${(refunded+BigInt(amountCents)).toString()}::bigint>=amount_cents then 'REFUNDED' else status end,revision=revision+1 where id=${paymentId}`);return {id:refund.id,lost:p.refund_mode==='TIMEOUT_AFTER_ACCEPT'};});
  if(result.lost)throw new ProviderUncertain('SIMULATED_REFUND_RESPONSE_LOST');return {id:result.id};}
 async get(tenant:string,a:Attempt,id:string){requireSimulation();const facts=await this.search(tenant,a);const f=facts.find(f=>f.id===id);if(!f)throw new Error('Authoritative payment absent');return f;}
}
export async function settle(tx:Transaction,tenant:string,a:Attempt,f:PaymentFact){
 const o=await order(tx,a.order_id,true);
 if(f.seller_id!==a.seller_id||f.environment!==a.environment||f.reference!==a.id){await incident(tx,tenant,o.id,'GATEWAY_IDENTITY_MISMATCH',`identity-${a.id}-${f.id}`);await event(tx,tenant,o,'PAYMENT_QUARANTINED','Vendedor/ambiente/referência incompatível.');return;}
 const approved=!!f.approved_at;
 if(!approved){await tx.execute(sql`update shop.payment_attempts set status=case when status='APPROVED' then status else ${['PENDING','REJECTED','CANCELLED','EXPIRED'].includes(f.status)?f.status:'UNKNOWN'} end,external_id=${f.id},raw_status=${f.status},last_checked_at=now(),next_check_at=now()+case when created_at>now()-interval '30 minutes' then interval '2 minutes' when created_at>now()-interval '6 hours' then interval '10 minutes' else interval '1 hour' end,lease_until=null where id=${a.id}`);return;}
 const [existing]=await rows<{id:string}>(tx,sql`select id from shop.payment_transactions where provider=${a.provider} and account_id=${a.account_id} and environment=${a.environment} and external_id=${f.id}`);
 const compatible=f.currency===a.currency&&f.amount_cents===a.expected_cents;let transactionId=existing?.id;
 if(!transactionId){transactionId=newId();const classification=!compatible?'INCOMPATIBLE':o.principal_id?'EXCESS':'PRINCIPAL';await tx.execute(sql`insert into shop.payment_transactions(id,tenant_id,order_id,attempt_id,account_id,provider,environment,external_id,received_cents,currency,classification,approved_at) values(${transactionId},${tenant},${o.id},${a.id},${a.account_id},${a.provider},${a.environment},${f.id},${f.amount_cents},${f.currency},${classification},${f.approved_at})`);
 if(!compatible){await incident(tx,tenant,o.id,'PAYMENT_VALUE_MISMATCH',`value-${f.id}`,transactionId,f.amount_cents);await incident(tx,tenant,o.id,'REFUND_ACTION_REQUIRED',`refund-${f.id}`,transactionId,f.amount_cents);}
 else if(o.principal_id){await incident(tx,tenant,o.id,'EXCESS_PAYMENT',`excess-${f.id}`,transactionId,f.amount_cents);await incident(tx,tenant,o.id,'REFUND_ACTION_REQUIRED',`refund-${f.id}`,transactionId,f.amount_cents);}
 else {await tx.execute(sql`update shop.orders set principal_id=${transactionId},payment_status='PAID' where id=${o.id}`);
 if(o.order_status==='CANCELLED'||o.cancel_requested_at){await endReservations(tx,tenant,o.id,false);await incident(tx,tenant,o.id,'REFUND_ACTION_REQUIRED',`refund-${f.id}`,transactionId,f.amount_cents);}
 else {await notify(tx,tenant,'PAYMENT_CONFIRMED',`paid-${o.id}`,{orderId:o.id});if(!await endReservations(tx,tenant,o.id,true)){const items=await rows<Item>(tx,sql`select variant_id,quantity,price_cents::text from shop.order_items where order_id=${o.id} order by variant_id`);if(!await allocate(tx,tenant,o.id,items,true)){await incident(tx,tenant,o.id,'PAID_WITHOUT_STOCK',`stock-${f.id}`,transactionId,f.amount_cents);await incident(tx,tenant,o.id,'REFUND_ACTION_REQUIRED',`refund-${f.id}`,transactionId,f.amount_cents);}}}
 }
 await event(tx,tenant,o,'PAYMENT_RECEIVED','Recebimento autoritativo preservado.');
 }
 await tx.execute(sql`update shop.payment_attempts set status='APPROVED',external_id=${f.id},raw_status=${f.status},last_checked_at=now(),next_check_at=now()+interval '1 day',lease_until=null where id=${a.id}`);
 for(const refund of f.refunds){if(!/^[1-9]\d*$/.test(refund.amount_cents))throw new Error('Invalid refund amount');const [old]=await rows<{amount_cents:string}>(tx,sql`select amount_cents::text from shop.payment_refunds where transaction_id=${transactionId} and external_id=${refund.id}`);if(old&&old.amount_cents!==refund.amount_cents){await incident(tx,tenant,o.id,'REFUND_VALUE_MISMATCH',`refund-value-${refund.id}`,transactionId);continue;}await tx.execute(sql`insert into shop.payment_refunds(id,tenant_id,transaction_id,external_id,amount_cents,confirmed_at) values(${newId()},${tenant},${transactionId},${refund.id},${refund.amount_cents},${new Date(refund.confirmed_at)}) on conflict(tenant_id,transaction_id,external_id) do nothing`);
  // A platform-initiated refund is CONFIRMED only when the provider lists it.
  await tx.execute(sql`update shop.refund_requests set status='CONFIRMED',provider_refund_id=${refund.id},updated_at=now() where transaction_id=${transactionId} and status<>'CONFIRMED' and (provider_refund_id=${refund.id} or operation_key=${refund.key??'-'})`);}
 const [sum]=await rows<{value:string}>(tx,sql`select coalesce(sum(amount_cents),0)::text as value from shop.payment_refunds where transaction_id=${transactionId}`);const refunded=BigInt(sum!.value),received=BigInt(f.amount_cents);
 if(refunded>received)await incident(tx,tenant,o.id,'REFUND_VALUE_MISMATCH',`refund-over-${f.id}`,transactionId);
 if(refunded>0n){const before=await order(tx,o.id);if(before.principal_id===transactionId&&before.payment_status!=='CHARGED_BACK'){await tx.execute(sql`update shop.orders set payment_status=${refunded>=received?'REFUNDED':'PARTIALLY_REFUNDED'} where id=${o.id}`);if(refunded<received)await incident(tx,tenant,o.id,'PARTIAL_REFUND_REVIEW',`partial-${f.id}`,transactionId);}
 await tx.execute(sql`update shop.order_incidents set due_cents=greatest(${received.toString()}::bigint-${refunded.toString()}::bigint,0),status=case when ${refunded>=received} then 'RESOLVED' else status end,resolved_at=case when ${refunded>=received} then now() else resolved_at end where transaction_id=${transactionId} and code in ('REFUND_ACTION_REQUIRED','EXCESS_PAYMENT','PAYMENT_VALUE_MISMATCH','PAID_WITHOUT_STOCK')`);
 if(JSON.stringify(dimensions(before))!==JSON.stringify(dimensions(await order(tx,o.id))))await event(tx,tenant,before,'REFUND_CONFIRMED','Devolução externa confirmada; sem reposição física.');}
 if(f.dispute){const before=await order(tx,o.id);await tx.execute(sql`insert into shop.payment_disputes(id,tenant_id,transaction_id,external_id,status,financial_loss) values(${newId()},${tenant},${transactionId},${f.dispute.id},${f.dispute.status},${f.dispute.financial_loss}) on conflict(tenant_id,transaction_id,external_id) do update set status=case when shop.payment_disputes.status in ('WON','LOST') then shop.payment_disputes.status else excluded.status end,financial_loss=shop.payment_disputes.financial_loss or excluded.financial_loss,updated_at=now()`);
 const [d]=await rows<{status:string;financial_loss:boolean}>(tx,sql`select status,financial_loss from shop.payment_disputes where transaction_id=${transactionId} and external_id=${f.dispute.id}`);if(before.principal_id===transactionId){await tx.execute(sql`update shop.orders set dispute_status=${d!.status},payment_status=case when ${d!.financial_loss} then 'CHARGED_BACK' else payment_status end where id=${o.id}`);}if(JSON.stringify(dimensions(before))!==JSON.stringify(dimensions(await order(tx,o.id))))await event(tx,tenant,before,'DISPUTE_UPDATED','Disputa autoritativa independente.');}
 await tx.execute(sql`update shop.order_incidents set status='RESOLVED',resolved_at=now() where order_id=${o.id} and code='PAYMENT_UNCERTAIN'`);
}
// Rechecks back off with age (2 min → 10 min → 1 h) so pending Pix volume cannot starve new emissions.
export async function processAttempt(database:Database,tenant:string,id:string,gateway:Gateway=new SimulatedGateway(database)){
 // Claim locally, then release the transaction before any provider call. UNKNOWN survives a crash.
 const claim=await withTenant(database,tenant,null,async tx=>{const a=await attemptData(tx,id),o=await order(tx,a.order_id,true);const [lease]=await rows(tx,sql`select id from shop.payment_attempts where id=${id} and (lease_until is null or lease_until<now()) for update`);if(!lease)return null;let create=a.status==='PREPARED';
 if(create){const limit=new Date(o.reserved_at).getTime()+60*60000,expires=Date.now()+40*60000;if(o.order_status!=='OPEN'||o.cancel_requested_at||expires>limit){create=false;await tx.execute(sql`update shop.payment_attempts set status='EXPIRED',last_checked_at=now() where id=${id}`);}else{await tx.execute(sql`update shop.orders set reservation_expires_at=${new Date(expires)} where id=${o.id}`);await tx.execute(sql`update shop.payment_attempts set status='UNKNOWN' where id=${id}`);}}
 // An UNKNOWN creation may never have reached the provider: retry only with the same idempotency key while the reservation still holds.
 const [active]=await rows(tx,sql`select id from shop.inventory_reservations where order_id=${o.id} and status='ACTIVE' limit 1`);const recreate=a.status==='UNKNOWN'&&!a.external_id&&o.order_status==='OPEN'&&!o.cancel_requested_at&&!o.principal_id&&!!active;
 await tx.execute(sql`update shop.payment_attempts set lease_until=now()+interval '1 minute' where id=${id}`);return {a,create,recreate};});if(!claim)return;
 try{let facts=claim.create?[await gateway.create(tenant,claim.a)]:await gateway.search(tenant,claim.a);if(!facts.length&&claim.recreate)facts=[await gateway.create(tenant,claim.a)];await withTenant(database,tenant,null,async tx=>{for(const f of facts)await settle(tx,tenant,claim.a,f);await tx.execute(sql`update shop.payment_attempts set lease_until=null,last_checked_at=now(),next_check_at=now()+case when status='APPROVED' then interval '1 day' else case when created_at>now()-interval '30 minutes' then interval '2 minutes' when created_at>now()-interval '6 hours' then interval '10 minutes' else interval '1 hour' end end where id=${id}`);await tx.execute(sql`update shop.order_incidents set status='RESOLVED',resolved_at=now() where operation_key=${`gateway-${id}`} and status='OPEN'`);await expire(tx,tenant,claim.a.order_id);});}
 catch{await withTenant(database,tenant,null,async tx=>{await tx.execute(sql`update shop.payment_attempts set lease_until=null,next_check_at=now()+interval '30 seconds' where id=${id}`);await incident(tx,tenant,claim.a.order_id,'GATEWAY_UNAVAILABLE',`gateway-${id}`);await tx.execute(sql`update shop.order_incidents set status='OPEN',resolved_at=null where operation_key=${`gateway-${id}`}`);await expire(tx,tenant,claim.a.order_id);});}
}
export async function expire(tx:Transaction,tenant:string,id:string){const o=await order(tx,id,true);if(o.principal_id||new Date(o.reservation_expires_at).getTime()>Date.now())return;const attempts=await rows<{status:string;last_checked_at:Date|null}>(tx,sql`select status,last_checked_at from shop.payment_attempts where order_id=${id}`);const definitive=attempts.every(a=>['EXPIRED','REJECTED','CANCELLED'].includes(a.status)&&a.last_checked_at&&Date.now()-new Date(a.last_checked_at).getTime()<120000);if(!definitive&&Date.now()-new Date(o.reserved_at).getTime()<60*60000)return;
 if(await endReservations(tx,tenant,id,false)){await tx.execute(sql`update shop.orders set payment_status=case when ${definitive} then 'UNPAID' else payment_status end,order_status=case when ${definitive} then 'CANCELLED' else order_status end where id=${id}`);if(!definitive)await incident(tx,tenant,id,'PAYMENT_UNCERTAIN',`uncertain-${id}`);await event(tx,tenant,o,'RESERVATION_RELEASED',definitive?'Gateway confirmou encerramento.':'Retenção máxima atingida; compra bloqueada sob incerteza.');}}
export async function cancel(tx:Transaction,tenant:string,id:string,member:string,reason:string){const o=await order(tx,id,true);if(o.fulfillment_status!=='UNFULFILLED')throw new PurchaseError(409,'Entrega exige atendimento; não pode ser apagada.');if(o.order_status==='CANCELLED')return view(tx,id);if(!o.principal_id){const [pending]=await rows(tx,sql`select id from shop.payment_attempts where order_id=${id} and status not in ('EXPIRED','REJECTED','CANCELLED')`);if(pending)throw new PurchaseError(409,'Concilie e encerre as tentativas antes de cancelar.');}await tx.execute(sql`update shop.orders set order_status='CANCELLED',cancel_requested_at=now() where id=${id}`);await endReservations(tx,tenant,id,false);if(o.principal_id)await incident(tx,tenant,id,'REFUND_ACTION_REQUIRED',`cancel-${id}`,o.principal_id,o.total_cents);await event(tx,tenant,o,'ORDER_CANCELLED',reason,member);await notify(tx,tenant,'ORDER_CANCELLED',`cancelled-${id}`,{orderId:id});return view(tx,id);}
export async function protocol(tx:Transaction,tenant:string,id:string,key:string,kind:string,message:string){const o=await order(tx,id,true),fingerprint=hash(JSON.stringify({kind,message}));const [old]=await rows<{id:string;fingerprint:string;created_at:Date}>(tx,sql`select id,fingerprint,created_at from shop.consumer_requests where order_id=${id} and operation_key=${key}`);if(old){if(old.fingerprint!==fingerprint)throw new PurchaseError(409,'Protocolo com conteúdo diferente.');return {...old,acknowledgement:'Solicitação recebida; não confirma cancelamento nem devolução financeira.'};}const [request]=await rows<{id:string;kind:string;created_at:Date}>(tx,sql`insert into shop.consumer_requests(id,tenant_id,order_id,operation_key,fingerprint,kind,message) values(${newId()},${tenant},${id},${key},${fingerprint},${kind},${message}) returning id,kind,created_at`);if(['CANCELLATION','WITHDRAWAL'].includes(kind))await tx.execute(sql`update shop.orders set cancel_requested_at=coalesce(cancel_requested_at,now()) where id=${id}`);await event(tx,tenant,o,'CONSUMER_REQUEST_RECEIVED','Solicitação durável com confirmação em tela.');await tx.execute(sql`insert into shop.support_messages(id,tenant_id,request_id,author,body) values(${newId()},${tenant},${request!.id},'CONSUMER',${message})`);await notify(tx,tenant,'REQUEST_RECEIVED',`request-${request!.id}`,{orderId:id,context:{protocol:request!.id,kind}});return {...request,acknowledgement:'Solicitação recebida; não confirma cancelamento nem devolução financeira.'};}
export async function consume(database:Database,tenant:string,eventId:string){await withTenant(database,tenant,null,async tx=>{const [e]=await rows<{aggregate_id:string;type:string}>(tx,sql`select aggregate_id,type from shop.purchase_outbox where id=${eventId} for update`);if(!e)throw new Error('Event not in tenant');const [receipt]=await rows(tx,sql`select id from shop.purchase_receipts where event_id=${eventId} and consumer='purchase-v1'`);if(receipt)return;
 // The local effect is scheduling reconciliation; the receipt commits with that effect.
 if(e.type==='CHECKOUT_CREATED')await tx.execute(sql`update shop.payment_attempts set next_check_at=now() where order_id=${e.aggregate_id} and status='PREPARED'`);
 await tx.execute(sql`insert into shop.purchase_receipts(id,tenant_id,event_id,consumer) values(${newId()},${tenant},${eventId},'purchase-v1')`);await tx.execute(sql`update shop.purchase_outbox set executed_at=now() where id=${eventId}`);});}
export async function routes(database:Database){return (await database.pool.query('select tenant_id from shop.purchase_routes()')).rows as {tenant_id:string}[];}
export function signature(secret:string,id:string,requestId:string,ts:string){return createHmac('sha256',secret).update(`id:${id};request-id:${requestId};ts:${ts};`).digest('hex');}
export function validateSignature(secret:string,id:string,requestId:string,header:string){const fields=Object.fromEntries(header.split(',').map(s=>s.trim().split('='))),ts=fields.ts||'',mac=fields.v1||'';if(!/^\d{13}$/.test(ts)||Math.abs(Date.now()-Number(ts))>300000||!/^[a-f0-9]{64}$/.test(mac))return false;return timingSafeEqual(Buffer.from(mac,'hex'),Buffer.from(signature(secret,id,requestId,ts),'hex'));}
export async function receiveWebhook(database:Database,accountId:string,eventId:string,resourceId:string,requestId:string,header:string){requireSimulation();const [route]=(await database.pool.query('select * from shop.payment_route($1)',[accountId])).rows;if(!route||route.provider!=='SIMULATED')throw new PurchaseError(404,'Conta não encontrada.');return withTenant(database,route.tenant_id,null,async tx=>{const [account]=await rows<{credentials_cipher:string}>(tx,sql`select credentials_cipher from shop.payment_accounts where id=${accountId}`);const secret=decrypt(account!.credentials_cipher,`${route.tenant_id}:${accountId}`);if(!validateSignature(secret,resourceId,requestId,header))throw new PurchaseError(401,'Assinatura inválida.');await tx.execute(sql`insert into shop.payment_inbox(id,tenant_id,account_id,event_id,resource_id) values(${newId()},${route.tenant_id},${accountId},${eventId},${resourceId}) on conflict(tenant_id,account_id,event_id) do nothing`);return {received:true};});}
export async function processInbox(database:Database,tenant:string){const inbox=await withTenant(database,tenant,null,tx=>rows<{id:string;account_id:string;resource_id:string}>(tx,sql`select id,account_id,resource_id from shop.payment_inbox where processed_at is null order by received_at limit 50`));for(const i of inbox){try{await inboxItem(database,tenant,i);}catch{console.error(JSON.stringify({event:'payment_inbox_retry',tenant_id:tenant}));}}}
async function inboxItem(database:Database,tenant:string,i:{id:string;account_id:string;resource_id:string}){{const [ref]=await withTenant(database,tenant,null,tx=>rows<{reference:string}>(tx,sql`select reference from shop.simulated_payments where id=${i.resource_id} and account_id=${i.account_id}`));if(!ref){await withTenant(database,tenant,null,tx=>tx.execute(sql`update shop.payment_inbox set processed_at=now(),quarantine_reason='UNKNOWN_RESOURCE' where id=${i.id}`));return;}const a=await withTenant(database,tenant,null,tx=>attemptData(tx,ref.reference));const fact=await new SimulatedGateway(database).get(tenant,a,i.resource_id);await withTenant(database,tenant,null,async tx=>{await settle(tx,tenant,a,fact);await tx.execute(sql`update shop.payment_inbox set processed_at=now() where id=${i.id}`);});}}
export async function newAttempt(tx:Transaction,tenant:string,orderId:string,method:'PIX'|'CARD',key:string){const o=await order(tx,orderId,true);const [same]=await rows<{id:string;method:string}>(tx,sql`select id,method from shop.payment_attempts where order_id=${o.id} and operation_key=${`retry-${o.id}-${key}`}`);if(same){if(same.method!==method)throw new PurchaseError(409,'Chave reutilizada com conteúdo diferente.');return same.id;}
 // A new charge is only allowed when every previous attempt is provably closed; UNKNOWN/PENDING block it.
 const [open]=await rows(tx,sql`select id from shop.payment_attempts where order_id=${o.id} and status not in ('REJECTED','CANCELLED','EXPIRED')`);const [active]=await rows(tx,sql`select id from shop.inventory_reservations where order_id=${o.id} and status='ACTIVE' limit 1`);
 await assertSalesOpen(tx);if(open||o.principal_id||o.order_status!=='OPEN'||o.cancel_requested_at||!active||new Date(o.reservation_expires_at).getTime()<=Date.now())throw new PurchaseError(409,'Nova tentativa indisponível: conclua a conciliação da tentativa anterior ou refaça a compra.');
 const [account]=await rows<{id:string}>(tx,sql`select id from shop.payment_accounts where provider='SIMULATED' and environment='SIMULATED' and status='CONNECTED' for share`);if(!account)throw new PurchaseError(409,'Conta de pagamento desconectada; novas cobranças bloqueadas.');
 const attempt=newId();await tx.execute(sql`insert into shop.payment_attempts(id,tenant_id,order_id,account_id,method,operation_key,expected_cents,currency) values(${attempt},${tenant},${o.id},${account.id},${method},${`retry-${o.id}-${key}`},${o.total_cents},'BRL')`);await event(tx,tenant,o,'PAYMENT_ATTEMPT_CREATED','Nova tentativa após encerramento confirmado da anterior.');return attempt;}
export async function correctAddress(tx:Transaction,tenant:string,orderId:string,member:string,address:unknown,reason:string){const o=await order(tx,orderId,true);if(!['UNFULFILLED','PROCESSING'].includes(o.fulfillment_status)||o.order_status==='CANCELLED')throw new PurchaseError(409,'Endereço só pode ser corrigido antes do envio.');await tx.execute(sql`insert into shop.order_address_corrections(id,tenant_id,order_id,address,reason,actor_membership_id) values(${newId()},${tenant},${o.id},${JSON.stringify(address)}::jsonb,${reason},${member})`);await event(tx,tenant,o,'ADDRESS_CORRECTED',reason,member);return view(tx,o.id);}
export * from './operations.js';
export * from './billing.js';
// ---- Reembolso iniciado pela plataforma (Fase 6, T18). Intenção persistida antes da chamada; limite serializado pelo lock do pedido.
export async function requestRefund(database:Database,tenant:string,input:{orderId:string;transactionId:string;amountCents:string;key:string;reason:string;member:string},gateway:Gateway=new SimulatedGateway(database)){
 if(!gateway.refund)throw new PurchaseError(409,'Devolução pela plataforma indisponível para este provedor; use o painel do gateway.');
 if(!/^[1-9]\d{0,17}$/.test(input.amountCents))throw new PurchaseError(400,'Valor inválido.');
 const intent=await withTenant(database,tenant,null,async tx=>{const o=await order(tx,input.orderId,true);const fingerprint=hash(JSON.stringify({t:input.transactionId,a:input.amountCents}));
  const [old]=await rows<{id:string;fingerprint:string;status:string}>(tx,sql`select id,fingerprint,status from shop.refund_requests where operation_key=${input.key}`);if(old){if(old.fingerprint!==fingerprint)throw new PurchaseError(409,'Chave reutilizada com conteúdo diferente.');return old;}
  if(o.dispute_status==='OPEN')throw new PurchaseError(409,'Disputa aberta: a devolução segue o processo de contestação do gateway.');
  const [t]=await rows<{received_cents:string;classification:string}>(tx,sql`select received_cents::text,classification from shop.payment_transactions where id=${input.transactionId} and order_id=${o.id}`);if(!t)throw new PurchaseError(404,'Recebimento não encontrado neste pedido.');
  if(o.payment_status==='CHARGED_BACK'&&o.principal_id===input.transactionId)throw new PurchaseError(409,'Recebimento contestado: não há saldo reembolsável.');
  // Remaining = received − confirmed refunds (including those done at the gateway panel) − requests still open.
  const [b]=await rows<{confirmed:string;open:string}>(tx,sql`select coalesce((select sum(amount_cents) from shop.payment_refunds where transaction_id=${input.transactionId}),0)::text as confirmed,coalesce((select sum(amount_cents) from shop.refund_requests where transaction_id=${input.transactionId} and status in ('REQUESTED','UNKNOWN','PENDING')),0)::text as open`);
  const available=BigInt(t.received_cents)-BigInt(b!.confirmed)-BigInt(b!.open);if(BigInt(input.amountCents)>available)throw new PurchaseError(409,`Valor excede o saldo reembolsável (${available} centavos, considerando devoluções confirmadas e solicitações em aberto).`);
  const id=newId();await tx.execute(sql`insert into shop.refund_requests(id,tenant_id,order_id,transaction_id,amount_cents,operation_key,fingerprint,reason,actor_membership_id) values(${id},${tenant},${o.id},${input.transactionId},${input.amountCents},${input.key},${fingerprint},${input.reason},${input.member})`);
  await event(tx,tenant,o,'REFUND_REQUESTED',`Devolução de ${input.amountCents} centavos solicitada pela plataforma.`,input.member);return {id,fingerprint,status:'REQUESTED'};});
 if(['REQUESTED','UNKNOWN'].includes(intent.status))await executeRefund(database,tenant,intent.id,gateway);
 return withTenant(database,tenant,null,async tx=>(await rows(tx,sql`select id,status,amount_cents::text,provider_refund_id,failure_reason,created_at from shop.refund_requests where id=${intent.id}`))[0]);
}
export async function executeRefund(database:Database,tenant:string,requestId:string,gateway:Gateway=new SimulatedGateway(database)){
 const ctx=await withTenant(database,tenant,null,async tx=>{const [r]=await rows<{id:string;status:string;amount_cents:string;operation_key:string;transaction_id:string;order_id:string;attempt_id:string;external_id:string}>(tx,sql`select r.id,r.status,r.amount_cents::text,r.operation_key,r.transaction_id,r.order_id,t.attempt_id,t.external_id from shop.refund_requests r join shop.payment_transactions t on (t.tenant_id,t.id)=(r.tenant_id,r.transaction_id) where r.id=${requestId} for update of r`);
  if(!r||!['REQUESTED','UNKNOWN'].includes(r.status))return null;await tx.execute(sql`update shop.refund_requests set status='UNKNOWN',updated_at=now() where id=${r.id}`);return {r,a:await attemptData(tx,r.attempt_id),previous:r.status};});
 if(!ctx)return;const {r,a}=ctx;
 // After an uncertain outcome, consult the provider first; the retry reuses the same idempotency key.
 if(ctx.previous==='UNKNOWN'){try{const fact=await gateway.get(tenant,a,r.external_id);if(fact.refunds.some(x=>x.key===r.operation_key)){await withTenant(database,tenant,null,tx=>settle(tx,tenant,a,fact));return;}}catch{return;}}
 try{const result=await gateway.refund!(tenant,a,r.external_id,r.amount_cents,r.operation_key);
  await withTenant(database,tenant,null,tx=>tx.execute(sql`update shop.refund_requests set status=case when status='CONFIRMED' then status else 'PENDING' end,provider_refund_id=${result.id},updated_at=now() where id=${r.id}`));
  const fact=await gateway.get(tenant,a,r.external_id);await withTenant(database,tenant,null,tx=>settle(tx,tenant,a,fact));}
 catch(error){if(error instanceof ProviderRejected){await withTenant(database,tenant,null,async tx=>{await tx.execute(sql`update shop.refund_requests set status='FAILED',failure_reason=${error.message.slice(0,80)},updated_at=now() where id=${r.id}`);await incident(tx,tenant,r.order_id,'REFUND_FAILED',`refund-failed-${r.id}`,r.transaction_id,r.amount_cents);const o=await order(tx,r.order_id);await event(tx,tenant,o,'REFUND_FAILED',`Gateway recusou a devolução: ${error.message.slice(0,80)}.`);});}
  // Timeout/unknown keeps UNKNOWN: it blocks the balance and is retried only after a consultation.
  else await withTenant(database,tenant,null,tx=>incident(tx,tenant,r.order_id,'REFUND_UNCERTAIN',`refund-uncertain-${r.id}`,r.transaction_id,r.amount_cents));}
}
export async function resumeRefunds(database:Database,tenant:string,gateway?:Gateway){const pending=await withTenant(database,tenant,null,tx=>rows<{id:string}>(tx,sql`select id from shop.refund_requests where status in ('REQUESTED','UNKNOWN') and updated_at<now()-interval '1 minute' order by created_at limit 20`));for(const p of pending){try{await executeRefund(database,tenant,p.id,gateway);}catch{console.error(JSON.stringify({event:'refund_resume_failed',tenant_id:tenant}));}}
 await withTenant(database,tenant,null,tx=>tx.execute(sql`update shop.order_incidents i set status='RESOLVED',resolved_at=now() where i.status='OPEN' and i.code='REFUND_UNCERTAIN' and exists(select 1 from shop.refund_requests r where i.operation_key='refund-uncertain-'||r.id and r.status in ('CONFIRMED','FAILED','PENDING'))`));}
export * from './domains.js';
export * from './shipping.js';
export * from './ai.js';
