import { createHash, randomBytes } from 'node:crypto';
import { newId, rows, sql, withTenant, type Database, type Transaction } from '@ecommerce/database';
import { event, order, PurchaseError, view, type Order } from './index.js';
import { notify } from './notifications.js';
const digest=(v:string)=>createHash('sha256').update(v).digest('hex');
// GATEWAY_UNAVAILABLE is operational noise; every other open incident is a financial or stock impediment.
export async function impediments(tx:Transaction,o:Order){
 const reasons:string[]=[];
 if(o.order_status!=='OPEN')reasons.push('Pedido não está aberto.');
 if(o.payment_status!=='PAID'||!o.principal_id)reasons.push('Pagamento principal não confirmado ou com devolução/contestação.');
 if(!['NONE','WON'].includes(o.dispute_status))reasons.push('Disputa em andamento.');
 for(const i of await rows<{code:string}>(tx,sql`select distinct code from shop.order_incidents where order_id=${o.id} and status='OPEN' and code<>'GATEWAY_UNAVAILABLE' order by code`))reasons.push(`Pendência ${i.code} aberta.`);
 const [request]=await rows(tx,sql`select id from shop.consumer_requests where order_id=${o.id} and kind in ('CANCELLATION','WITHDRAWAL') and status<>'RESOLVED' limit 1`);if(request)reasons.push('Solicitação de cancelamento/arrependimento em aberto.');
 const [active]=await rows(tx,sql`select id from shop.inventory_reservations where order_id=${o.id} and status='ACTIVE' limit 1`);if(active)reasons.push('Estoque ainda não baixado.');
 return reasons;
}
async function releasable(tx:Transaction,o:Order){const reasons=await impediments(tx,o);if(reasons.length)throw new PurchaseError(409,`Entrega bloqueada: ${reasons.join(' ')}`);}
async function fulfillment(tx:Transaction,id:string,status:string){await tx.execute(sql`update shop.orders set fulfillment_status=${status},order_status=case when ${status==='DELIVERED'} then 'COMPLETED' else order_status end where id=${id}`);}
const kindOf=async(tx:Transaction,id:string)=>(await rows<{kind:string}>(tx,sql`select shipping->>'kind' as kind from shop.orders where id=${id}`))[0]!.kind;
export async function startProcessing(tx:Transaction,tenant:string,id:string,member:string){const o=await order(tx,id,true);if(o.fulfillment_status!=='UNFULFILLED')throw new PurchaseError(409,'Separação já iniciada.');await releasable(tx,o);await fulfillment(tx,id,'PROCESSING');await event(tx,tenant,o,'FULFILLMENT_PROCESSING','Separação iniciada após conferência de pagamento e impedimentos.',member);return view(tx,id);}
export async function ship(tx:Transaction,tenant:string,id:string,member:string,carrier:string,tracking:string){const o=await order(tx,id,true);if(o.fulfillment_status!=='PROCESSING')throw new PurchaseError(409,'Envio exige pedido em separação.');if(await kindOf(tx,id)==='PICKUP')throw new PurchaseError(409,'Pedido de retirada não usa transportadora.');await releasable(tx,o);
 await tx.execute(sql`insert into shop.shipments(id,tenant_id,order_id,kind,carrier,tracking_code,shipped_at,actor_membership_id) values(${newId()},${tenant},${id},'CARRIER',${carrier},${tracking||null},now(),${member})`);await fulfillment(tx,id,'SHIPPED');await event(tx,tenant,o,'ORDER_SHIPPED',`Envio por ${carrier}.`,member);await notify(tx,tenant,'SHIPPED',`shipped-${id}`,{orderId:id,context:{carrier,tracking}});return view(tx,id);}
export async function readyForPickup(tx:Transaction,tenant:string,id:string,member:string){const o=await order(tx,id,true);if(o.fulfillment_status!=='PROCESSING'||await kindOf(tx,id)!=='PICKUP')throw new PurchaseError(409,'Disponível apenas para retirada em separação.');await releasable(tx,o);
 await tx.execute(sql`insert into shop.shipments(id,tenant_id,order_id,kind,ready_at,actor_membership_id) values(${newId()},${tenant},${id},'PICKUP',now(),${member})`);await event(tx,tenant,o,'READY_FOR_PICKUP','Pedido pronto para retirada.',member);await notify(tx,tenant,'READY_FOR_PICKUP',`pickup-${id}`,{orderId:id});return view(tx,id);}
export async function deliver(tx:Transaction,tenant:string,id:string,member:string,proof:string){const o=await order(tx,id,true);const [s]=await rows<{kind:string;ready_at:Date|null}>(tx,sql`select kind,ready_at from shop.shipments where order_id=${id} for update`);
 if(!s||(s.kind==='CARRIER'&&o.fulfillment_status!=='SHIPPED')||(s.kind==='PICKUP'&&(o.fulfillment_status!=='PROCESSING'||!s.ready_at)))throw new PurchaseError(409,'Entrega exige envio registrado ou retirada pronta.');
 if(s.kind==='PICKUP'){if(proof.length<3)throw new PurchaseError(400,'Informe a comprovação da retirada.');await releasable(tx,o);}
 await tx.execute(sql`update shop.shipments set delivered_at=now(),delivery_proof=${proof||null} where order_id=${id}`);await fulfillment(tx,id,'DELIVERED');await event(tx,tenant,o,'ORDER_DELIVERED',s.kind==='PICKUP'?'Retirada comprovada.':'Entrega confirmada.',member);await notify(tx,tenant,'DELIVERED',`delivered-${id}`,{orderId:id});return view(tx,id);}
export async function registerReturn(tx:Transaction,tenant:string,id:string,member:string,note:string){const o=await order(tx,id,true);if(!['SHIPPED','DELIVERED'].includes(o.fulfillment_status))throw new PurchaseError(409,'Devolução física exige envio ou entrega registrados.');
 // Physical return never restocks automatically; restocking is an explicit inventory adjustment.
 await tx.execute(sql`update shop.shipments set returned_at=now(),return_note=${note} where order_id=${id}`);await fulfillment(tx,id,'RETURNED');await event(tx,tenant,o,'ORDER_RETURNED',note,member);return view(tx,id);}
export async function resolveOperational(tx:Transaction,tenant:string,id:string,incidentId:string,member:string,note:string){const o=await order(tx,id,true);
 // Only non-financial reviews can be closed by a person; refunds/excess/mismatch close only on gateway confirmation.
 const [row]=await rows(tx,sql`update shop.order_incidents set status='RESOLVED',resolved_at=now(),note=${note},actor_membership_id=${member} where id=${incidentId} and order_id=${id} and status='OPEN' and code in ('PARTIAL_REFUND_REVIEW','GATEWAY_IDENTITY_MISMATCH','GATEWAY_UNAVAILABLE','REFUND_FAILED') returning id`);if(!row)throw new PurchaseError(409,'Esta pendência só é resolvida por confirmação do gateway ou realocação.');await event(tx,tenant,o,'INCIDENT_REVIEWED',note,member);return view(tx,id);}
export async function requestReconciliation(tx:Transaction,tenant:string,id:string,member:string){const o=await order(tx,id,true);await tx.execute(sql`update shop.payment_attempts set next_check_at=now(),lease_until=null where order_id=${id}`);await event(tx,tenant,o,'RECONCILIATION_REQUESTED','Nova consulta ao gateway solicitada.',member);return view(tx,id);}
export async function setFiscalReference(tx:Transaction,tenant:string,id:string,member:string,reference:string){const o=await order(tx,id,true);await tx.execute(sql`update shop.orders set fiscal_reference=${reference} where id=${id}`);await event(tx,tenant,o,'FISCAL_REFERENCE','Referência de documento fiscal externo registrada.',member);return view(tx,id);}
// ---- Atendimento (seção 22.5) ----
export async function contact(tx:Transaction,tenant:string,input:{name:string;email:string;message:string;key:string}){
 const fingerprint=digest(JSON.stringify({name:input.name,email:input.email,message:input.message}));const [old]=await rows<{id:string;fingerprint:string;created_at:Date}>(tx,sql`select id,fingerprint,created_at from shop.consumer_requests where order_id is null and operation_key=${input.key}`);
 if(old){if(old.fingerprint!==fingerprint)throw new PurchaseError(409,'Protocolo com conteúdo diferente.');return {id:old.id,created_at:old.created_at,token:null,acknowledgement:'Solicitação já registrada; use o código de acompanhamento recebido.'};}
 const token=randomBytes(24).toString('base64url'),id=newId();const [r]=await rows<{created_at:Date;due_at:Date}>(tx,sql`insert into shop.consumer_requests(id,tenant_id,order_id,operation_key,fingerprint,kind,message,contact_name,contact_email,access_hash) values(${id},${tenant},null,${input.key},${fingerprint},'CONTACT',${input.message},${input.name},${input.email},${digest(token)}) returning created_at,due_at`);
 await tx.execute(sql`insert into shop.support_messages(id,tenant_id,request_id,author,body) values(${newId()},${tenant},${id},'CONSUMER',${input.message})`);await notify(tx,tenant,'REQUEST_RECEIVED',`request-${id}`,{requestId:id,context:{protocol:id,kind:'CONTACT'}});
 return {id,created_at:r!.created_at,due_at:r!.due_at,token,acknowledgement:'Protocolo registrado. Guarde o código de acompanhamento; ele não é enviado novamente.'};
}
export async function contactByToken(tx:Transaction,id:string,token:string){const [r]=await rows<{id:string}>(tx,sql`select id from shop.consumer_requests where id=${id} and order_id is null and access_hash=${digest(token)}`);if(!r)throw new PurchaseError(404,'Protocolo não autorizado.');return ticket(tx,id,false);}
export async function ticket(tx:Transaction,id:string,staff:boolean){const [r]=await rows<Record<string,unknown>>(tx,sql`select id,order_id,kind,status,outcome,resolution,created_at,due_at,resolved_at,contact_name,contact_email,assignee_membership_id,financial_notified_at,financial_reference from shop.consumer_requests where id=${id}`);if(!r)throw new PurchaseError(404,'Protocolo não encontrado.');
 const messages=await rows<Record<string,unknown>>(tx,sql`select id,author,body,created_at${staff?sql`,actor_membership_id`:sql``} from shop.support_messages where request_id=${id} order by created_at,id`);
 if(!staff){delete r.assignee_membership_id;delete r.financial_reference;delete r.contact_email;}return {...r,messages};}
export async function consumerReply(tx:Transaction,tenant:string,id:string,body:string){const [r]=await rows<{status:string}>(tx,sql`select status from shop.consumer_requests where id=${id}`);if(!r)throw new PurchaseError(404,'Protocolo não encontrado.');if(r.status==='RESOLVED')throw new PurchaseError(409,'Protocolo concluído; abra uma nova solicitação.');await tx.execute(sql`insert into shop.support_messages(id,tenant_id,request_id,author,body) values(${newId()},${tenant},${id},'CONSUMER',${body})`);return ticket(tx,id,false);}
async function targetOf(tx:Transaction,id:string){const [r]=await rows<{order_id:string|null;kind:string;status:string}>(tx,sql`select order_id,kind,status from shop.consumer_requests where id=${id} for update`);if(!r)throw new PurchaseError(404,'Protocolo não encontrado.');return r;}
export async function staffList(tx:Transaction,filter:string){return rows(tx,sql`select r.id,r.order_id,o.number::text as order_number,r.kind,r.status,r.created_at,r.due_at,r.due_at<now() and r.status<>'RESOLVED' as overdue,r.assignee_membership_id,(r.kind in ('WITHDRAWAL','CANCELLATION') and o.principal_id is not null and r.financial_notified_at is null and r.status<>'RESOLVED') as financial_action_required from shop.consumer_requests r left join shop.orders o on (o.tenant_id,o.id)=(r.tenant_id,r.order_id) where ${filter==='all'?sql`true`:filter==='overdue'?sql`r.status<>'RESOLVED' and r.due_at<now()`:sql`r.status<>'RESOLVED'`} order by r.due_at limit 100`);}
export async function assign(tx:Transaction,id:string,member:string){await targetOf(tx,id);await tx.execute(sql`update shop.consumer_requests set assignee_membership_id=${member},status=case when status='OPEN' then 'IN_PROGRESS' else status end where id=${id} and status<>'RESOLVED'`);return ticket(tx,id,true);}
export async function staffReply(tx:Transaction,tenant:string,id:string,member:string,body:string){const r=await targetOf(tx,id);if(r.status==='RESOLVED')throw new PurchaseError(409,'Protocolo concluído.');const message=newId();await tx.execute(sql`insert into shop.support_messages(id,tenant_id,request_id,author,actor_membership_id,body) values(${message},${tenant},${id},'STAFF',${member},${body})`);await tx.execute(sql`update shop.consumer_requests set status='IN_PROGRESS',assignee_membership_id=coalesce(assignee_membership_id,${member}) where id=${id}`);
 await notify(tx,tenant,'SUPPORT_REPLY',`reply-${message}`,{orderId:r.order_id,requestId:r.order_id?null:id,context:{protocol:id,reply:body}});return ticket(tx,id,true);}
export async function resolveRequest(tx:Transaction,tenant:string,id:string,member:string,outcome:string,resolution:string){const r=await targetOf(tx,id);if(r.status==='RESOLVED')return ticket(tx,id,true);
 if(r.order_id&&['WITHDRAWAL','CANCELLATION'].includes(r.kind)&&outcome==='ACCEPTED'){const [o]=await rows<{order_status:string;principal_id:string|null}>(tx,sql`select order_status,principal_id from shop.orders where id=${r.order_id}`);const [f]=await rows<{financial_notified_at:Date|null}>(tx,sql`select financial_notified_at from shop.consumer_requests where id=${id}`);
  if(o!.principal_id&&!f!.financial_notified_at)throw new PurchaseError(409,'Registre a comunicação ao meio de pagamento antes de concluir o arrependimento/cancelamento aceito.');}
 await tx.execute(sql`update shop.consumer_requests set status='RESOLVED',outcome=${outcome},resolution=${resolution},resolved_at=now(),assignee_membership_id=coalesce(assignee_membership_id,${member}) where id=${id}`);await tx.execute(sql`insert into shop.support_messages(id,tenant_id,request_id,author,actor_membership_id,body) values(${newId()},${tenant},${id},'STAFF',${member},${resolution})`);
 // A declined/withdrawn cancellation releases the shipping block it created; accepted ones keep the order for explicit cancellation/return.
 if(r.order_id&&outcome!=='ACCEPTED'){const [other]=await rows(tx,sql`select id from shop.consumer_requests where order_id=${r.order_id} and kind in ('WITHDRAWAL','CANCELLATION') and status<>'RESOLVED' limit 1`);if(!other)await tx.execute(sql`update shop.orders set cancel_requested_at=null where id=${r.order_id} and order_status='OPEN'`);}
 if(r.order_id){const o=await order(tx,r.order_id);await event(tx,tenant,o,'CONSUMER_REQUEST_RESOLVED',`${outcome}: ${resolution}`,member);}
 await notify(tx,tenant,'REQUEST_RESOLVED',`resolved-${id}`,{orderId:r.order_id,requestId:r.order_id?null:id,context:{protocol:id,resolution}});return ticket(tx,id,true);}
export async function financialCommunication(tx:Transaction,tenant:string,id:string,member:string,reference:string){const r=await targetOf(tx,id);if(!r.order_id||!['WITHDRAWAL','CANCELLATION'].includes(r.kind))throw new PurchaseError(409,'Comunicação financeira aplica-se a arrependimento/cancelamento de pedido.');
 await tx.execute(sql`update shop.consumer_requests set financial_notified_at=coalesce(financial_notified_at,now()),financial_reference=${reference},financial_actor_membership_id=${member} where id=${id}`);const o=await order(tx,r.order_id);await event(tx,tenant,o,'FINANCIAL_COMMUNICATION','Comunicação ao meio de pagamento registrada; não confirma devolução.',member);return ticket(tx,id,true);}
// ---- Privacidade ----
export async function exportStore(tx:Transaction){return {generated_at:new Date().toISOString(),orders:await rows(tx,sql`select o.id,o.number::text,o.created_at,o.order_status,o.payment_status,o.fulfillment_status,o.dispute_status,o.total_cents::text,o.buyer,o.address,o.fiscal_reference,(select coalesce(jsonb_agg(jsonb_build_object('sku',i.snapshot->>'sku','name',i.snapshot->>'name','quantity',i.quantity,'price_cents',i.price_cents::text)),'[]') from shop.order_items i where i.order_id=o.id) as items,(select coalesce(jsonb_agg(jsonb_build_object('received_cents',t.received_cents::text,'classification',t.classification,'external_id',t.external_id)),'[]') from shop.payment_transactions t where t.order_id=o.id) as payments from shop.orders o order by o.number`),requests:await rows(tx,sql`select id,order_id,kind,status,created_at,resolved_at,outcome from shop.consumer_requests order by created_at`)};}
export async function exportConsumer(tx:Transaction,orderId:string){const o=await order(tx,orderId);const email=(o as unknown as {buyer:{email:string}}).buyer.email;return {generated_at:new Date().toISOString(),orders:await rows(tx,sql`select id,number::text,created_at,buyer,address,total_cents::text,order_status,payment_status,fulfillment_status from shop.orders where buyer->>'email'=${email} order by number`),requests:await rows(tx,sql`select r.id,r.kind,r.message,r.created_at,r.status from shop.consumer_requests r join shop.orders x on (x.tenant_id,x.id)=(r.tenant_id,r.order_id) where x.buyer->>'email'=${email}`)};}
export async function createExport(tx:Transaction,tenant:string,member:string,kind:'STORE'|'CONSUMER',orderId:string|null){const token=randomBytes(32).toString('base64url'),id=newId();await tx.execute(sql`insert into shop.data_exports(id,tenant_id,kind,order_id,token_hash,actor_membership_id,expires_at) values(${id},${tenant},${kind},${orderId},${digest(token)},${member},now()+interval '15 minutes')`);return {id,token,expires_in_seconds:900};}
export async function readExport(tx:Transaction,id:string,token:string){const [e]=await rows<{kind:string;order_id:string|null;expired:boolean}>(tx,sql`select kind,order_id,expires_at<=now() as expired from shop.data_exports where id=${id} and token_hash=${digest(token)} for update`);if(!e)throw new PurchaseError(404,'Exportação não encontrada.');if(e.expired)throw new PurchaseError(410,'Link de exportação expirado; gere outro.');await tx.execute(sql`update shop.data_exports set downloaded_at=now() where id=${id}`);return e.kind==='STORE'?exportStore(tx):exportConsumer(tx,e.order_id!);}
const ANON={name:'ANONIMIZADO',email:'anonimizado@invalid'},ANON_ADDRESS={cep:'00000000',street:'ANONIMIZADO',number:'-',city:'-',state:'--',complement:''};
export async function erasureBlockers(tx:Transaction,orderId:string){const o=await order(tx,orderId);const reasons:string[]=[];if(o.order_status==='OPEN')reasons.push('Pedido em andamento.');if(o.dispute_status==='OPEN')reasons.push('Disputa aberta.');const [i]=await rows(tx,sql`select id from shop.order_incidents where order_id=${orderId} and status='OPEN' limit 1`);if(i)reasons.push('Pendência financeira/operacional aberta.');return reasons;}
// Idempotent: used for the original request and to reapply the ledger after restoring an older backup.
export async function applyErasure(tx:Transaction,orderId:string){
 await tx.execute(sql`update shop.orders set buyer=${JSON.stringify(ANON)}::jsonb,address=${JSON.stringify(ANON_ADDRESS)}::jsonb where id=${orderId}`);
 await tx.execute(sql`update shop.order_address_corrections set address=${JSON.stringify(ANON_ADDRESS)}::jsonb where order_id=${orderId}`);
 await tx.execute(sql`update shop.support_messages set body='[removido]' where request_id in (select id from shop.consumer_requests where order_id=${orderId}) and author='CONSUMER'`);
 await tx.execute(sql`update shop.consumer_requests set message='[removido]',contact_name=null,contact_email=null where order_id=${orderId}`);
 await tx.execute(sql`update shop.notifications set recipient=${ANON.email},body='[removido]',subject='[removido]',status=case when status='PENDING' then 'HELD' else status end where order_id=${orderId}`);
 await tx.execute(sql`update shop.order_access_tokens set revoked_at=coalesce(revoked_at,now()) where order_id=${orderId}`);
}
export async function erase(tx:Transaction,tenant:string,orderId:string,member:string,reason:string,erasureId:string){const blockers=await erasureBlockers(tx,orderId);if(blockers.length)throw new PurchaseError(409,`Eliminação bloqueada por retenção justificada: ${blockers.join(' ')}`);
 await applyErasure(tx,orderId);await tx.execute(sql`insert into shop.privacy_erasures(id,tenant_id,order_id,actor_membership_id,reason) values(${erasureId},${tenant},${orderId},${member},${reason}) on conflict(tenant_id,order_id) do nothing`);const o=await order(tx,orderId);await event(tx,tenant,o,'PERSONAL_DATA_ERASED','Dados pessoais anonimizados; fatos financeiros preservados.',member);return {erased:true,order_id:orderId};}
// ---- Operação ----
export async function operationRoutes(database:Database){return (await database.pool.query('select tenant_id from shop.operation_routes()')).rows as {tenant_id:string}[];}
export type TenantStatus={tenant_id:string;outbox_oldest_seconds:number;outbox_failed:number;inbox_oldest_seconds:number;notifications_pending:number;notifications_oldest_seconds:number;notifications_failed:number;financial_incidents:number;payment_uncertain:number;support_overdue:number;financial_communication_pending:number;suspended:boolean;sales_paused:boolean};
export async function tenantStatus(database:Database,tenant:string){return withTenant(database,tenant,null,async tx=>(await rows<TenantStatus>(tx,sql`select ${tenant}::uuid as tenant_id,
 coalesce(extract(epoch from now()-(select min(occurred_at) from shop.purchase_outbox where executed_at is null)),0)::int as outbox_oldest_seconds,
 (select count(*)::int from shop.purchase_outbox where executed_at is null and failures>=5) as outbox_failed,
 coalesce(extract(epoch from now()-(select min(received_at) from shop.payment_inbox where processed_at is null)),0)::int as inbox_oldest_seconds,
 (select count(*)::int from shop.notifications where status='PENDING') as notifications_pending,
 coalesce(extract(epoch from now()-(select min(created_at) from shop.notifications where status='PENDING')),0)::int as notifications_oldest_seconds,
 (select count(*)::int from shop.notifications where status='FAILED') as notifications_failed,
 (select count(*)::int from shop.order_incidents where status='OPEN' and code in ('REFUND_ACTION_REQUIRED','EXCESS_PAYMENT','PAYMENT_VALUE_MISMATCH','PAID_WITHOUT_STOCK','REFUND_VALUE_MISMATCH','GATEWAY_IDENTITY_MISMATCH')) as financial_incidents,
 (select count(*)::int from shop.order_incidents where status='OPEN' and code='PAYMENT_UNCERTAIN') as payment_uncertain,
 (select count(*)::int from shop.consumer_requests where status<>'RESOLVED' and due_at<now()) as support_overdue,
 (select count(*)::int from shop.consumer_requests r join shop.orders o on (o.tenant_id,o.id)=(r.tenant_id,r.order_id) where r.kind in ('WITHDRAWAL','CANCELLATION') and r.status<>'RESOLVED' and o.principal_id is not null and r.financial_notified_at is null) as financial_communication_pending,
 (select lifecycle_status='SUSPENDED' from shop.tenants where id=${tenant}) as suspended,(select sales_paused_at is not null from shop.tenants where id=${tenant}) as sales_paused`))[0]!);}
// Thresholds are deliberately conservative for the pilot; each code maps to a procedure in docs/operacao/alertas.md.
export function alerts(s:TenantStatus){const out:{code:string;severity:'critical'|'warning';value:number}[]=[];const add=(code:string,severity:'critical'|'warning',value:number,when:boolean)=>{if(when)out.push({code,severity,value});};
 add('OUTBOX_BACKLOG','warning',s.outbox_oldest_seconds,s.outbox_oldest_seconds>300);add('OUTBOX_FAILED','critical',s.outbox_failed,s.outbox_failed>0);add('INBOX_BACKLOG','critical',s.inbox_oldest_seconds,s.inbox_oldest_seconds>300);
 add('NOTIFICATION_BACKLOG','warning',s.notifications_oldest_seconds,s.notifications_oldest_seconds>900);add('NOTIFICATION_FAILED','warning',s.notifications_failed,s.notifications_failed>0);
 add('FINANCIAL_INCIDENT_OPEN','critical',s.financial_incidents,s.financial_incidents>0);add('PAYMENT_UNCERTAIN','critical',s.payment_uncertain,s.payment_uncertain>0);
 add('SUPPORT_OVERDUE','warning',s.support_overdue,s.support_overdue>0);add('FINANCIAL_COMMUNICATION_PENDING','critical',s.financial_communication_pending,s.financial_communication_pending>0);return out;}
// After restoring an older point: hold queued e-mail for review and turn PREPARED attempts into UNKNOWN so the worker consults before charging.
export async function postRestore(database:Database,tenant:string,reason:string){return withTenant(database,tenant,null,async tx=>{const held=await tx.execute(sql`update shop.notifications set status='HELD' where status='PENDING'`);const unknown=await tx.execute(sql`update shop.payment_attempts set status='UNKNOWN',next_check_at=now(),lease_until=null where status='PREPARED'`);await tx.execute(sql`update shop.payment_attempts set next_check_at=now(),lease_until=null where status in ('PENDING','UNKNOWN','APPROVED')`);
 await tx.execute(sql`update shop.tenants set sales_paused_at=coalesce(sales_paused_at,now()),sales_pause_reason=${reason} where id=${tenant}`);await tx.execute(sql`insert into shop.tenant_lifecycle_events(id,tenant_id,action,reason,actor) values(${newId()},${tenant},'SALES_PAUSED',${reason},'OPERATOR:post-restore')`);return {held:held.rowCount??0,unknown:unknown.rowCount??0};});}
// ---- Observação do piloto (Fase 5): agregados por loja, sem dados pessoais nem conteúdo de mensagens.
export type PilotReport={tenant_id:string;period:{from:string;to:string};published:boolean;lifecycle:string;sales_paused:boolean;orders:{created:number;paid:number;completed:number;cancelled:number;gmv_paid_cents:string};checkout_failures:Record<string,number>;checkout_success_rate:number|null;incidents:{opened:number;resolved:number;open_now:number;median_resolution_minutes:number|null;by_code:Record<string,number>};refunds:{count:number;amount_cents:string};support:{requests:number;resolved:number;overdue_now:number;median_first_response_hours:number|null;median_resolution_hours:number|null;staff_minutes:number;by_category:Record<string,number>};notifications:{sent_or_simulated:number;failed:number;pending:number};media_bytes:string;sample_note:string};
export async function pilotReport(database:Database,tenant:string,from:Date,to:Date):Promise<PilotReport>{return withTenant(database,tenant,null,async tx=>{
 const one=async<T>(q:ReturnType<typeof sql>)=>(await rows<T>(tx,q))[0]!;
 const t=await one<{lifecycle_status:string;sales_paused:boolean;published:boolean}>(sql`select t.lifecycle_status,t.sales_paused_at is not null as sales_paused,exists(select 1 from shop.storefronts s where s.published_revision_id is not null) as published from shop.tenants t where t.id=${tenant}`);
 const o=await one<{created:number;paid:number;completed:number;cancelled:number;gmv:string}>(sql`select count(*)::int as created,count(*) filter(where principal_id is not null)::int as paid,count(*) filter(where order_status='COMPLETED')::int as completed,count(*) filter(where order_status='CANCELLED')::int as cancelled,coalesce(sum(total_cents) filter(where principal_id is not null),0)::text as gmv from shop.orders where created_at>=${from} and created_at<${to}`);
 const failures=Object.fromEntries((await rows<{reason:string;n:number}>(tx,sql`select reason,count(*)::int as n from shop.checkout_failures where created_at>=${from} and created_at<${to} group by reason order by reason`)).map(r=>[r.reason,r.n]));
 const failed=Object.values(failures).reduce((s,n)=>s+n,0);
 const i=await one<{opened:number;resolved:number;open_now:number;median:number|null}>(sql`select count(*) filter(where created_at>=${from} and created_at<${to})::int as opened,count(*) filter(where resolved_at>=${from} and resolved_at<${to})::int as resolved,count(*) filter(where status='OPEN')::int as open_now,(percentile_cont(0.5) within group(order by extract(epoch from resolved_at-created_at)/60) filter(where resolved_at>=${from} and resolved_at<${to}))::float as median from shop.order_incidents where code<>'GATEWAY_UNAVAILABLE'`);
 const byCode=Object.fromEntries((await rows<{code:string;n:number}>(tx,sql`select code,count(*)::int as n from shop.order_incidents where created_at>=${from} and created_at<${to} group by code order by code`)).map(r=>[r.code,r.n]));
 const r=await one<{count:number;amount:string}>(sql`select count(*)::int as count,coalesce(sum(amount_cents),0)::text as amount from shop.payment_refunds where confirmed_at>=${from} and confirmed_at<${to}`);
 const s=await one<{requests:number;resolved:number;overdue:number;first:number|null;resolution:number|null}>(sql`select count(*) filter(where r.created_at>=${from} and r.created_at<${to})::int as requests,count(*) filter(where r.resolved_at>=${from} and r.resolved_at<${to})::int as resolved,count(*) filter(where r.status<>'RESOLVED' and r.due_at<now())::int as overdue,
  (percentile_cont(0.5) within group(order by extract(epoch from (select min(m.created_at) from shop.support_messages m where m.request_id=r.id and m.author='STAFF')-r.created_at)/3600) filter(where r.created_at>=${from} and r.created_at<${to} and exists(select 1 from shop.support_messages m where m.request_id=r.id and m.author='STAFF')))::float as first,
  (percentile_cont(0.5) within group(order by extract(epoch from r.resolved_at-r.created_at)/3600) filter(where r.resolved_at>=${from} and r.resolved_at<${to}))::float as resolution from shop.consumer_requests r`);
 const minutes=Object.fromEntries((await rows<{category:string;n:number}>(tx,sql`select category,sum(minutes)::int as n from shop.support_time_entries where occurred_at>=${from} and occurred_at<${to} group by category order by category`)).map(x=>[x.category,x.n]));
 const n=await one<{sent:number;failed:number;pending:number}>(sql`select count(*) filter(where status in ('SENT','SIMULATED'))::int as sent,count(*) filter(where status='FAILED')::int as failed,count(*) filter(where status='PENDING')::int as pending from shop.notifications where created_at>=${from} and created_at<${to}`);
 const m=await one<{bytes:string}>(sql`select coalesce(sum(stored_bytes),0)::text as bytes from shop.media_assets where status<>'DELETED'`);
 const attempts=o.created+failed,round=(v:number|null)=>v===null?null:Math.round(v*10)/10;
 return {tenant_id:tenant,period:{from:from.toISOString(),to:to.toISOString()},published:t.published,lifecycle:t.lifecycle_status,sales_paused:t.sales_paused,orders:{created:o.created,paid:o.paid,completed:o.completed,cancelled:o.cancelled,gmv_paid_cents:o.gmv},checkout_failures:failures,checkout_success_rate:attempts?Math.round(o.created/attempts*1000)/10:null,
  incidents:{opened:i.opened,resolved:i.resolved,open_now:i.open_now,median_resolution_minutes:round(i.median),by_code:byCode},refunds:{count:r.count,amount_cents:r.amount},support:{requests:s.requests,resolved:s.resolved,overdue_now:s.overdue,median_first_response_hours:round(s.first),median_resolution_hours:round(s.resolution),staff_minutes:Object.values(minutes).reduce((a,b)=>a+b,0),by_category:minutes},
  notifications:{sent_or_simulated:n.sent,failed:n.failed,pending:n.pending},media_bytes:m.bytes,sample_note:o.created<20?'Amostra pequena: indicadores inconclusivos.':'Amostra suficiente para tendência, não para estatística fina.'};});}
export async function recordSupportTime(database:Database,tenant:string,minutes:number,category:string,note:string,actor:string){if(!Number.isInteger(minutes)||minutes<1||minutes>1440)throw new Error('Minutos entre 1 e 1440.');if(/@|\d{5,}/.test(note))throw new Error('Nota não pode conter e-mail ou números identificáveis.');return withTenant(database,tenant,null,async tx=>{const id=newId();await tx.execute(sql`insert into shop.support_time_entries(id,tenant_id,minutes,category,note,actor) values(${id},${tenant},${minutes},${category},${note},${actor})`);return {id,minutes,category};});}
