'use client';
import { FormEvent, useEffect, useState } from 'react';
import { money } from './storefront';
type Quote={id:string;method:string;price_cents:string;total_cents:string;expires_at:string;days:number};
type Address={cep:string;street:string;number:string;city:string;state:string;complement:string};
type OrderData={id:string;number:string;order_status:string;payment_status:string;fulfillment_status:string;dispute_status:string;subtotal_cents:string;shipping_cents:string;total_cents:string;created_at:string;reservation_expires_at:string;simulation:boolean;buyer:{name:string;email:string};address:Address;supplier:Record<string,string>;shipping:{name:string;kind:string;days:number};items:{variant_id:string;quantity:number;price_cents:string;snapshot:{name:string;sku:string;attributes:Record<string,string>}}[];attempts:{id:string;method:string;status:string;environment:string}[];transactions:{id:string;received_cents:string;classification:string;refunded_cents:string}[];incidents:{id:string;code:string;status:string}[];protocols:{id:string;kind:string;message:string;status:string;created_at:string;due_at:string}[]};
const fields=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;};
async function call(slug:string,path:string,body?:unknown,extra:Record<string,string>={}){const response=await fetch(`/api/public/stores/${slug}/${path}`,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...extra},body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(typeof data.error==='string'?data.error:data.error?.message||'Não foi possível concluir.');return data;}
// randomUUID requires a secure context; getRandomValues works on plain HTTP previews too.
const uid=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
// One key per confirmed intent: a reload or double click repeats the same operation instead of buying twice.
function intentKey(quote:string){const name=`checkout-${quote}`;let key='';try{key=sessionStorage.getItem(name)||'';}catch{}if(!key){key=uid();try{sessionStorage.setItem(name,key);}catch{}}return key;}
const labels:Record<string,string>={OPEN:'Aberto',COMPLETED:'Concluído',CANCELLED:'Cancelado',UNPAID:'Não pago',PENDING:'Aguardando confirmação',PAID:'Pago',PARTIALLY_REFUNDED:'Parcialmente devolvido',REFUNDED:'Devolvido',CHARGED_BACK:'Contestado',UNFULFILLED:'Não enviado',PROCESSING:'Em separação',SHIPPED:'Enviado',DELIVERED:'Entregue',RETURNED:'Devolvido à loja',NONE:'Sem disputa',WON:'Disputa vencida',LOST:'Disputa perdida'};
export function Checkout({slug,quote,subtotal,address}:{slug:string;quote:Quote;subtotal:string;address:Address}){
 const [step,setStep]=useState<'form'|'review'>('form'),[buyer,setBuyer]=useState({name:'',email:'',method:'PIX'}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[methods,setMethods]=useState<{simulation:boolean;reason:string}|null>(null);
 useEffect(()=>{call(slug,'payment-methods').then(setMethods).catch(()=>setMethods(null));},[slug]);
 if(!methods?.simulation)return <aside className="local">Pagamento indisponível: {methods?.reason||'consultando meios habilitados…'} Nenhum pedido será criado.</aside>;
 async function confirm(){setBusy(true);setError('');try{const order=await call(slug,'cart/checkout',{key:intentKey(quote.id),quote_id:quote.id,address,buyer:{name:buyer.name,email:buyer.email},method:buyer.method,total_cents:quote.total_cents});location.assign(`/lojas/${slug}/pedidos/${order.id}`);}catch(e){setError((e as Error).message);setBusy(false);}}
 return <section aria-label="Finalizar compra"><h3>Finalizar compra</h3><aside className="local">Ambiente SIMULADO: nenhum valor real é cobrado. Meios de pagamento reais aguardam homologação do Mercado Pago.</aside>
  {step==='form'?<form aria-label="Dados do comprador" onSubmit={e=>{const b=fields(e);setBuyer({name:b.name!,email:b.email!,method:b.method!});setStep('review');}}><label>Nome completo<input name="name" required maxLength={100} defaultValue={buyer.name} autoComplete="name"/></label><label>E-mail para comprovante<input name="email" type="email" required maxLength={200} defaultValue={buyer.email} autoComplete="email"/></label><label>Pagamento<select name="method" defaultValue={buyer.method}><option value="PIX">Pix (simulado)</option><option value="CARD">Cartão (simulado)</option></select></label><button>Revisar pedido</button></form>
  :<div><h4>Revise antes de confirmar</h4><dl><dt>Comprador</dt><dd>{buyer.name} · {buyer.email}</dd><dt>Entrega</dt><dd>{quote.method} · {quote.days} dia(s) · {address.street}, {address.number} {address.complement} — {address.city}/{address.state} · CEP {address.cep}</dd><dt>Pagamento</dt><dd>{buyer.method==='PIX'?'Pix':'Cartão'} (simulado)</dd><dt>Subtotal</dt><dd>{money(subtotal)}</dd><dt>Frete</dt><dd>{money(quote.price_cents)}</dd><dt>Total a pagar</dt><dd><strong>{money(quote.total_cents)}</strong></dd></dl><p>Ao confirmar você aceita as políticas do fornecedor exibidas no rodapé. O estoque fica reservado por até 40 minutos aguardando o pagamento.</p><div className="row"><button type="button" disabled={busy} onClick={()=>setStep('form')}>Corrigir dados</button><button type="button" disabled={busy} onClick={()=>void confirm()}>Confirmar compra de {money(quote.total_cents)}</button></div></div>}
  {error&&<p role="alert" className="error">{error}</p>}</section>;
}
type Ticket={id:string;kind:string;status:string;outcome:string|null;resolution:string|null;created_at:string;due_at:string;messages:{id:string;author:string;body:string;created_at:string}[]};
const kinds:Record<string,string>={SUPPORT:'Atendimento',WITHDRAWAL:'Arrependimento',CANCELLATION:'Cancelamento',DATA_ACCESS:'Acesso aos meus dados',DATA_ERASURE:'Eliminação dos meus dados',CONTACT:'Contato'};
const states:Record<string,string>={OPEN:'Aberto',IN_PROGRESS:'Em atendimento',RESOLVED:'Concluído'};
// The e-mail link carries its secret in the fragment; it is moved to sessionStorage and removed from the address bar.
function accessHeader(orderId:string):Record<string,string>{let token='';try{const hash=new URLSearchParams(location.hash.slice(1)).get('acesso')||'';if(hash){sessionStorage.setItem(`acesso-${orderId}`,hash);history.replaceState(null,'',location.pathname);}token=sessionStorage.getItem(`acesso-${orderId}`)||'';}catch{}return token?{'X-Order-Token':token}:{};}
function Thread({slug,orderId,id,auth}:{slug:string;orderId:string;id:string;auth:Record<string,string>}){
 const [ticket,setTicket]=useState<Ticket|null>(null),[error,setError]=useState('');
 useEffect(()=>{call(slug,`orders/${orderId}/requests/${id}`,undefined,auth).then(setTicket).catch(e=>setError(e.message));},[slug,orderId,id]);
 if(!ticket)return error?<p className="error">{error}</p>:null;
 return <div><ul>{ticket.messages.map(m=><li key={m.id}><small>{m.author==='STAFF'?'Loja':'Você'} · {new Date(m.created_at).toLocaleString('pt-BR')}</small><p className="prose">{m.body}</p></li>)}</ul>
  {ticket.status!=='RESOLVED'?<form aria-label={`Responder protocolo ${ticket.id}`} onSubmit={e=>{const b=fields(e),form=e.currentTarget;void call(slug,`orders/${orderId}/requests/${id}/messages`,{body:b.body},auth).then(t=>{setTicket(t);form.reset();}).catch(e=>setError(e.message));}}><label>Responder<textarea name="body" required maxLength={4000}/></label><button>Enviar resposta</button></form>:<p>Resultado: {ticket.resolution}</p>}{error&&<p className="error" role="alert">{error}</p>}</div>;
}
type Shipment={kind:string;carrier:string|null;tracking_code:string|null;ready_at:string|null;shipped_at:string|null;delivered_at:string|null};
export function OrderView({slug,orderId}:{slug:string;orderId:string}){
 const [order,setOrder]=useState<OrderData&{shipment:Shipment|null;protocols:{id:string;kind:string;status:string;created_at:string;due_at:string}[]}|null>(null),[error,setError]=useState(''),[ack,setAck]=useState(''),[busy,setBusy]=useState(false),[auth,setAuth]=useState<Record<string,string>>({}),[open,setOpen]=useState('');
 async function load(headers=auth){try{setOrder(await call(slug,`orders/${orderId}`,undefined,headers));setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{const headers=accessHeader(orderId);setAuth(headers);void load(headers);const timer=setInterval(()=>void load(headers),5000);return ()=>clearInterval(timer);},[slug,orderId]);
 if(error&&!order)return <section><h2>Pedido</h2><p role="alert" className="error">{error}</p><p>Abra pelo navegador usado na compra ou pelo link recebido por e-mail.</p></section>;
 if(!order)return <p>Carregando pedido autorizado…</p>;
 const blocked=order.incidents.some(i=>i.status==='OPEN'),retry=order.order_status==='OPEN'&&order.payment_status!=='PAID'&&order.attempts.every(a=>['REJECTED','CANCELLED','EXPIRED'].includes(a.status)),s=order.shipment;
 return <section aria-label="Comprovante do pedido"><p className="eyebrow">{order.simulation?'COMPROVANTE · PAGAMENTO SIMULADO':'Comprovante'}</p><h2>Pedido nº {order.number}</h2><p>Realizado em {new Date(order.created_at).toLocaleString('pt-BR')}. Guarde esta página ou o link recebido por e-mail.</p>
  <dl><dt>Pedido</dt><dd>{labels[order.order_status]}</dd><dt>Pagamento</dt><dd>{labels[order.payment_status]}</dd><dt>Entrega</dt><dd>{labels[order.fulfillment_status]}</dd>{order.dispute_status!=='NONE'&&<><dt>Disputa</dt><dd>{labels[order.dispute_status]}</dd></>}</dl>
  {s&&<p role="status">{s.kind==='PICKUP'?(s.delivered_at?`Retirado em ${new Date(s.delivered_at).toLocaleString('pt-BR')}.`:s.ready_at?'Pronto para retirada.':''):`Enviado por ${s.carrier}${s.tracking_code?` · rastreio ${s.tracking_code}`:''}${s.delivered_at?` · entregue em ${new Date(s.delivered_at).toLocaleString('pt-BR')}`:''}.`}</p>}
  {order.payment_status==='PENDING'&&order.order_status==='OPEN'&&<p role="status">Aguardando confirmação do pagamento pelo gateway. O retorno do navegador não confirma pagamento; esta página atualiza sozinha.</p>}
  {blocked&&<p role="status" className="local">Há uma pendência em análise pela loja. O envio fica bloqueado até a resolução.</p>}
  <h3>Itens</h3><ul>{order.items.map(i=><li key={i.variant_id}>{i.quantity} × {i.snapshot.name} · {i.snapshot.sku}{Object.keys(i.snapshot.attributes||{}).length?` (${Object.values(i.snapshot.attributes).join(' / ')})`:''} — {money(i.price_cents)}</li>)}</ul>
  <p>Subtotal {money(order.subtotal_cents)} · Frete {money(order.shipping_cents)} · <strong>Total {money(order.total_cents)}</strong></p>
  <p>Entrega: {order.shipping.name} · {order.address.street}, {order.address.number} — {order.address.city}/{order.address.state} · CEP {order.address.cep}</p>
  <p>Comprador: {order.buyer.name} · {order.buyer.email}</p><p>Fornecedor: {order.supplier.name} · {order.supplier.email} · {order.supplier.address}</p>
  {retry&&<button disabled={busy} onClick={()=>{setBusy(true);void call(slug,`orders/${orderId}/attempts`,{method:'PIX',key:uid()},auth).then(setOrder).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>Tentar pagar novamente</button>}
  <h3>Atendimento, cancelamento ou arrependimento</h3><p>Você recebe um protocolo imediato. Receber a solicitação não confirma cancelamento nem devolução de valores; a loja responde em até 5 dias. O arrependimento (art. 49 do CDC) pode ser pedido em até 7 dias do recebimento.</p>
  <form aria-label="Abrir solicitação" onSubmit={e=>{const b=fields(e),form=e.currentTarget;setBusy(true);setAck('');void call(slug,`orders/${orderId}/requests`,{kind:b.kind,message:b.message,key:uid()},auth).then(r=>{setAck(`Protocolo ${r.id} registrado em ${new Date(r.created_at).toLocaleString('pt-BR')}. ${r.acknowledgement}`);form.reset();void load();}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><label>Tipo<select name="kind"><option value="SUPPORT">Atendimento</option><option value="WITHDRAWAL">Arrependimento (art. 49 CDC)</option><option value="CANCELLATION">Cancelamento</option><option value="DATA_ACCESS">Acesso aos meus dados</option><option value="DATA_ERASURE">Eliminação dos meus dados</option></select></label><label>Mensagem<textarea name="message" required maxLength={2000}/></label><button disabled={busy}>Enviar solicitação</button></form>
  {ack&&<p role="status" className="success">{ack}</p>}{error&&<p role="alert" className="error">{error}</p>}
  {order.protocols.length>0&&<><h4>Protocolos</h4><ul>{order.protocols.map(p=><li key={p.id}><button className="link" onClick={()=>setOpen(open===p.id?'':p.id)}>{kinds[p.kind]||p.kind} · {states[p.status]||p.status} · {new Date(p.created_at).toLocaleString('pt-BR')}</button><small>Protocolo {p.id} · resposta até {new Date(p.due_at).toLocaleDateString('pt-BR')}</small>{open===p.id&&<Thread slug={slug} orderId={orderId} id={p.id} auth={auth}/>}</li>)}</ul></>}
 </section>;
}
export function ContactPage({slug}:{slug:string}){
 const [result,setResult]=useState<{id:string;token:string;created_at:string;due_at:string}|null>(null),[ticket,setTicket]=useState<Ticket|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const follow=(id:string,token:string)=>call(slug,`support/${id}`,undefined,{'X-Support-Token':token}).then(setTicket);
 return <section aria-label="Atendimento"><h2>Fale com a loja</h2><p>Use este formulário sem precisar de compra. Você recebe um protocolo e um código de acompanhamento na hora.</p>
  <form aria-label="Contato geral" onSubmit={e=>{const b=fields(e);setBusy(true);setError('');void call(slug,'support',{name:b.name,email:b.email,message:b.message,key:uid()}).then(r=>{setResult(r);return follow(r.id,r.token);}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><label>Nome<input name="name" required maxLength={100} autoComplete="name"/></label><label>E-mail<input name="email" type="email" required maxLength={200} autoComplete="email"/></label><label>Mensagem<textarea name="message" required maxLength={2000}/></label><button disabled={busy}>Enviar</button></form>
  {result&&<p role="status" className="success">Protocolo {result.id} registrado em {new Date(result.created_at).toLocaleString('pt-BR')}. Código de acompanhamento: <code>{result.token}</code>. Guarde-o; ele não é exibido de novo. Resposta até {new Date(result.due_at).toLocaleDateString('pt-BR')}.</p>}
  <h3>Acompanhar protocolo</h3><form aria-label="Acompanhar protocolo" onSubmit={e=>{const b=fields(e);setError('');void follow(b.id!,b.token!).catch(e=>setError(e.message));}}><label>Protocolo<input name="id" required/></label><label>Código de acompanhamento<input name="token" required/></label><button>Consultar</button></form>
  {ticket&&<div><p>{states[ticket.status]} · aberto em {new Date(ticket.created_at).toLocaleString('pt-BR')}</p><ul>{ticket.messages.map(m=><li key={m.id}><small>{m.author==='STAFF'?'Loja':'Você'}</small><p className="prose">{m.body}</p></li>)}</ul>{ticket.resolution&&<p>Resultado: {ticket.resolution}</p>}</div>}
  {error&&<p role="alert" className="error">{error}</p>}</section>;
}
