'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Checkout, ContactPage, OrderView } from './checkout';
export type Variant={id:string;sku:string;attributes:Record<string,string>;is_default:boolean;active:boolean;price_cents:string;available:number};
export type Product={id:string;name:string;slug:string;description:string;status:string;variants:Variant[];media:{id:string}[]};
export type Theme={title:string;description:string;hero:string;color:string;font:string;assets?:string[];pages:{slug:string;title:string;body:string}[];menu:{label:string;path:string}[];supplier?:{synthetic:boolean;name:string;document:string;address:string;email:string;phone:string;policies:string;delivery:string;risks:string}};
export type StoreData={route:{slug:string;canonical:string};theme:Theme;products:Product[];categories:{slug:string;name:string}[];noindex:boolean};
export const money=(value:string)=>{const cents=BigInt(value);return `R$ ${(cents/100n).toString().replace(/\B(?=(\d{3})+(?!\d))/g,'.')},${(cents%100n).toString().padStart(2,'0')}`;};
const fields=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget));};
async function api(slug:string,path:string,body?:unknown) {
  const response=await fetch(`/api/public/stores/${slug}/cart${path}`,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});
  const data=await response.json();if(!response.ok)throw new Error(typeof data.error==='string'?data.error:data.error?.message||'Não foi possível concluir.');return data;
}
function Add({slug,product}:{slug:string;product:Product}) {
  const variants=product.variants.filter(v=>v.active),[selected,setSelected]=useState(variants[0]?.id||''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [ready,setReady]=useState(false);useEffect(()=>setReady(true),[]);
  const variant=variants.find(v=>v.id===selected);
  return <form aria-label={`Adicionar ${product.name}`} onSubmit={e=>{const b=fields(e);setBusy(true);setError('');void api(slug,'/items',{variant_id:selected,quantity:Number(b.quantity)}).then(()=>setMessage('Variação adicionada ao carrinho.')).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>
    <label>Variação<select value={selected} onChange={e=>setSelected(e.target.value)}>{variants.map(v=><option key={v.id} value={v.id}>{Object.values(v.attributes).join(' / ')||'Padrão'} · {v.sku}</option>)}</select></label>
    {variant&&<p><strong>{money(variant.price_cents)}</strong> · Disponível: {variant.available}</p>}
    <label>Quantidade<input name="quantity" type="number" min="1" max={Math.min(99,variant?.available||1)} defaultValue="1" required/></label><button disabled={!ready||busy||!variant||variant.available<1}>Adicionar ao carrinho</button>{message&&<p role="status">{message} <a href={`/lojas/${slug}/carrinho`}>Ver carrinho</a></p>}{error&&<p role="alert" className="error">{error}</p>}
  </form>;
}
function Cart({slug}:{slug:string}) {
  type CartData={items:{variant_id:string;quantity:number;price_cents:string;name:string;sku:string;available:number;active:boolean;status:string}[];subtotal_cents:string;valid:boolean};
  const [cart,setCart]=useState<CartData|null>(null),[error,setError]=useState(''),[quote,setQuote]=useState<{id:string;method:string;price_cents:string;total_cents:string;expires_at:string;days:number}|null>(null),[busy,setBusy]=useState(false),[address,setAddress]=useState<any>(null);
  useEffect(()=>{api(slug,'').then(setCart).catch(e=>setError(e.message));},[slug]);
  async function change(variant_id:string,quantity:number){setBusy(true);setQuote(null);setError('');try{setCart(await api(slug,'/items',{variant_id,quantity}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section><h2>Seu carrinho</h2><p>Preços recalculados no servidor. Adicionar itens não reserva estoque.</p>{error&&<p className="error" role="alert">{error}</p>}{cart?<><ul>{cart.items.map(i=><li key={i.variant_id}><h3>{i.name} · {i.sku}</h3><p>{money(i.price_cents)} por unidade</p>{(!i.active||i.status!=='ACTIVE'||i.quantity>i.available)&&<p role="alert">Item indisponível ou quantidade acima do saldo. Revise.</p>}<form onSubmit={e=>{const b=fields(e);void change(i.variant_id,Number(b.quantity));}}><label>Quantidade de {i.name}<input name="quantity" type="number" min="0" max="99" defaultValue={i.quantity} required/></label><button disabled={busy}>Atualizar quantidade</button></form><button disabled={busy} onClick={()=>void change(i.variant_id,0)}>Remover {i.name}</button></li>)}</ul><p>Subtotal: <strong>{money(cart.subtotal_cents)}</strong></p>
    <h3>Consultar entrega</h3><form aria-label="Calcular frete" onSubmit={e=>{const b=fields(e),kind=b.kind;delete b.kind;setError('');setQuote(null);setBusy(true);setAddress({complement:'',...b,cep:String(b.cep).replace('-','')});void api(slug,'/quotes',{kind,address:b}).then(setQuote).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>
    <label>Método<select name="kind"><option value="TABLE">Entrega por tabela de CEP</option><option value="PICKUP">Retirada na loja</option><option value="CARRIER">Transportadora (cotação)</option></select></label><label>CEP<input name="cep" pattern="[0-9]{5}-?[0-9]{3}" required autoComplete="postal-code"/></label><label>Rua<input name="street" required autoComplete="street-address"/></label><label>Número<input name="number" required/></label><label>Cidade<input name="city" required autoComplete="address-level2"/></label><label>UF<input name="state" minLength={2} maxLength={2} required autoComplete="address-level1"/></label><label>Complemento<input name="complement"/></label><button disabled={busy||!cart.valid||cart.items.length===0}>Calcular frete</button></form>
    {quote&&<div role="status"><p>{quote.method}: {money(quote.price_cents)} · prazo {quote.days} dia(s)</p><p>Total: <strong>{money(quote.total_cents)}</strong></p><p>Cotação {quote.id} válida até {new Date(quote.expires_at).toLocaleTimeString('pt-BR')}. Mudanças exigem nova cotação.</p></div>}{quote&&address&&<Checkout slug={slug} quote={quote} subtotal={cart.subtotal_cents} address={address}/>}</>:<p>Carregando carrinho…</p>}</section>;
}
export default function Storefront({data,path=[],preview=false,previewTenant}:{data:StoreData;path?:string[];preview?:boolean;previewTenant?:string}) {
  const {theme,route}=data,base=`/lojas/${route.slug}`,product=path[0]==='produtos'?data.products.find(p=>p.slug===path[1]):null,page=path[0]==='paginas'?theme.pages.find(p=>p.slug===path[1]):null,supplier=theme.supplier;
  const mediaUrl=(asset:string,size:string)=>previewTenant?`/api/tenants/${previewTenant}/storefront/media/${asset}/${size}`:`/api/public/stores/${route.slug}/media/${asset}/${size}`;
  return <main data-store={route.slug} style={{'--brand':theme.color,fontFamily:theme.font==='serif'?'Georgia,serif':'system-ui,sans-serif'} as React.CSSProperties}>
    <a href="#conteudo">Ir para o conteúdo</a><header><p className="eyebrow">{preview?'PREVIEW PRIVADO':supplier?.synthetic?'LOJA SINTÉTICA · TESTE':'Loja independente'}</p><h1><a href={base}>{theme.title}</a></h1><p>{theme.description}</p>{theme.assets?.[0]&&<img className="product-image" src={mediaUrl(theme.assets[0],'large')} alt={theme.title} width="1280" height="480"/>}<nav aria-label="Navegação da loja" className="row">{theme.menu.map(m=><a key={m.path} href={`${base}${m.path==='/'?'':m.path}`}>{m.label}</a>)}<a href={`${base}/carrinho`}>Carrinho</a><a href={`${base}/atendimento`}>Atendimento</a><a href="/">Painel</a></nav></header>
    {preview&&<aside className="local">Rascunho autorizado — não publicado. Carrinho desabilitado no preview.</aside>}
    <div id="conteudo">{path[0]==='carrinho'?preview?<p>Não disponível no preview.</p>:<Cart slug={route.slug}/>:path[0]==='atendimento'?preview?<p>Não disponível no preview.</p>:<ContactPage slug={route.slug}/>:path[0]==='pedidos'&&path[1]?preview?<p>Não disponível no preview.</p>:<OrderView slug={route.slug} orderId={path[1]}/>:product?<section><h2>{product.name}</h2>{product.media.map(m=><img key={m.id} className="product-image" src={mediaUrl(m.id,'large')} alt={product.name} width="640" height="480"/>)}<p className="prose">{product.description}</p>{!preview&&<Add slug={route.slug} product={product}/>}<p>{supplier?.risks}</p></section>:page?<section><h2>{page.title}</h2><p className="prose">{page.body}</p></section>:<><section><h2>{theme.hero||'Conheça nosso catálogo'}</h2><form action={base} role="search"><label>Buscar produto ou SKU<input type="search" name="q" maxLength={100}/></label><button>Pesquisar</button></form><nav aria-label="Categorias" className="row"><a href={base}>Todos</a>{data.categories.map(c=><a key={c.slug} href={`${base}/categorias/${c.slug}`}>{c.name}</a>)}</nav></section><div className="grid">{data.products.map(p=><section key={p.id}>{p.media[0]&&<img className="product-image" src={mediaUrl(p.media[0].id,'small')} alt={p.name} width="480" height="360" loading="lazy"/>}<h2><a href={`${base}/produtos/${p.slug}`}>{p.name}</a></h2><p>{p.description.slice(0,150)}</p>{p.variants.filter(v=>v.active)[0]&&<p>A partir de {money(p.variants.filter(v=>v.active).reduce((min,v)=>BigInt(v.price_cents)<BigInt(min)?v.price_cents:min,p.variants.filter(v=>v.active)[0].price_cents))}</p>}<a href={`${base}/produtos/${p.slug}`}>Escolher variação</a></section>)}</div>{data.products.length===0&&<p>Nenhum produto encontrado nesta loja.</p>}</>}</div>
    {supplier&&<footer><section><h2>Fornecedor e atendimento</h2><strong>{supplier.name}</strong>{supplier.document&&<p>Documento: {supplier.document}</p>}<p>{supplier.address}</p><p><a href={`mailto:${supplier.email}`}>{supplier.email}</a> · {supplier.phone}</p><h3>Entrega e restrições</h3><p className="prose">{supplier.delivery}</p><h3>Políticas do fornecedor</h3><p className="prose">{supplier.policies}</p>{supplier.synthetic&&<p>Ambiente TESTE — contatos e políticas fictícios; não realiza vendas.</p>}</section></footer>}
  </main>;
}
