'use client';
import { FormEvent,use,useEffect,useState } from 'react';
import { MfaGate } from '../../../../components/mfa-gate';
import { money } from '../../../../components/storefront';
type Row={id:string;number:string;order_status:string;payment_status:string;fulfillment_status:string;dispute_status:string;total_cents:string;created_at:string;delivery_kind:string;open_incidents:number;refund_due_cents:string;open_requests:number};
type Detail=Row&{buyer:{name:string;email:string};fiscal_reference:string|null;shipping:{name:string;kind:string};items:{variant_id:string;quantity:number;price_cents:string;snapshot:{name:string;sku:string}}[];attempts:{id:string;method:string;status:string;provider:string;environment:string}[];transactions:{id:string;external_id:string;received_cents:string;classification:string;refunded_cents:string}[];incidents:{id:string;code:string;status:string;due_cents:string;note:string|null;transaction_id?:string}[];protocols:{id:string;kind:string;status:string;created_at:string}[];history:{event:string;reason:string;created_at:string}[];address_corrections:{reason:string;created_at:string}[];outbox_failures:number;shipment:{kind:string;carrier:string|null;tracking_code:string|null;ready_at:string|null;delivered_at:string|null}|null};
type Note={id:string;template:string;status:string;attempts:number;last_error:string|null};
const fields=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;};
const FINANCIAL=['REFUND_ACTION_REQUIRED','EXCESS_PAYMENT','PAYMENT_VALUE_MISMATCH','REFUND_VALUE_MISMATCH'],REVIEW=['PARTIAL_REFUND_REVIEW','GATEWAY_IDENTITY_MISMATCH','GATEWAY_UNAVAILABLE'];
export default function Orders({params}:{params:Promise<{tenantId:string}>}){
 const [mfaCsrf,setMfaCsrf]=useState('');
 const {tenantId}=use(params),[csrf,setCsrf]=useState(''),[orders,setOrders]=useState<Row[]|null>(null),[accounts,setAccounts]=useState<{id:string;provider:string;environment:string;status:string}[]>([]),[detail,setDetail]=useState<Detail|null>(null),[blocks,setBlocks]=useState<string[]>([]),[notes,setNotes]=useState<Note[]>([]),[filter,setFilter]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[owner,setOwner]=useState(false);
 async function api(path:string,method='GET',body?:unknown,token=csrf,extra:Record<string,string>={}){const response=await fetch(`/api/tenants/${tenantId}/${path}`,{method,cache:'no-store',headers:{...(method==='POST'?{'Content-Type':'application/json'}:{}),'X-CSRF-Token':token,...extra},body:method==='POST'?JSON.stringify(body||{}):undefined});const data=await response.json();if(!response.ok)throw new Error(typeof data.error==='string'?data.error:data.error?.message||'Acesso negado.');return data;}
 async function open(id:string,token=csrf){setDetail(await api(`purchase/orders/${id}`,'GET',undefined,token));setBlocks((await api(`operations/orders/${id}/impediments`,'GET',undefined,token)).impediments);setNotes(await api(`operations/orders/${id}/notifications`,'GET',undefined,token));}
 async function refresh(token=csrf,current=detail?.id,query=filter){setOrders(await api(`operations/orders${query}`,'GET',undefined,token));setAccounts(await api('purchase/accounts','GET',undefined,token));if(current)await open(current,token);}
 async function act(action:()=>Promise<unknown>,done='Ação registrada.'){setBusy(true);setError('');setNotice('');try{await action();await refresh();setNotice(done);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void fetch('/api/auth/session',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('Entre no painel para continuar.');const s=await r.json();if(s.mfa?.enabled&&!s.mfa.verified){setMfaCsrf(s.csrf);return;}setCsrf(s.csrf);const stores=await fetch('/api/tenants',{cache:'no-store'}).then(r=>r.json());setOwner(stores.some((t:{id:string;role:string})=>t.id===tenantId&&t.role==='OWNER'));await refresh(s.csrf,undefined,'');}).catch(e=>setError(e.message));},[tenantId]);
 const attempt=detail?.attempts.at(-1),d=detail,o=(path:string)=>`operations/orders/${d!.id}/${path}`;
 async function download(kind:'STORE'|'CONSUMER',orderId?:string){const e=await api('operations/exports','POST',{kind,order_id:orderId});const data=await api(`operations/exports/${e.id}`,'GET',undefined,csrf,{'X-Export-Token':e.token});const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`exportacao-${kind.toLowerCase()}-${e.id}.json`;a.click();URL.revokeObjectURL(url);}
 return <main><header><p className="eyebrow">Administração · Pedidos e pagamentos</p><h1>Pedidos</h1><nav className="row"><a href={`/painel/${tenantId}`}>Catálogo e vitrine</a><a href={`/painel/${tenantId}/atendimento`}>Atendimento</a><a href={`/painel/${tenantId}/operacao`}>Operação</a><a href="/">Lojas</a></nav></header>{error&&<p role="alert" className="error">{error}</p>}{mfaCsrf&&<MfaGate csrf={mfaCsrf}/>}{notice&&<p role="status" className="success">{notice}</p>}
 <section><h2>Conta de pagamento</h2><p>Mercado Pago real desabilitado até a homologação externa (Fase 0). Conta SIMULADA não movimenta dinheiro.</p><ul>{accounts.map(a=><li key={a.id}>{a.provider} · {a.environment} · {a.status} {owner&&a.status==='CONNECTED'&&<button disabled={busy} onClick={()=>void act(()=>api(`purchase/accounts/${a.id}/revoke`,'POST'),'Conta revogada; novas cobranças bloqueadas.')}>Revogar</button>}</li>)}</ul>{owner&&<button disabled={busy} onClick={()=>void act(()=>api('purchase/accounts/simulated','POST'),'Conta simulada conectada.')}>Conectar conta SIMULADA</button>}</section>
 <section><h2>Pedidos recentes</h2><form aria-label="Filtrar pedidos" className="row" onSubmit={e=>{const b=fields(e),q=new URLSearchParams(Object.entries(b).filter(([,v])=>v));const query=q.size?`?${q}`:'';setFilter(query);void act(()=>refresh(csrf,detail?.id,query),'Filtro aplicado.');}}><label>Pagamento<select name="payment_status"><option value="">Todos</option>{['PENDING','PAID','PARTIALLY_REFUNDED','REFUNDED','CHARGED_BACK','UNPAID'].map(v=><option key={v}>{v}</option>)}</select></label><label>Entrega<select name="fulfillment_status"><option value="">Todas</option>{['UNFULFILLED','PROCESSING','SHIPPED','DELIVERED','RETURNED'].map(v=><option key={v}>{v}</option>)}</select></label><label>Pedido<select name="order_status"><option value="">Todos</option>{['OPEN','COMPLETED','CANCELLED'].map(v=><option key={v}>{v}</option>)}</select></label><label>Número<input name="number" inputMode="numeric" pattern="[0-9]*"/></label><label>Somente com pendências<select name="pending"><option value="">Não</option><option value="true">Sim</option></select></label><button disabled={busy}>Filtrar</button></form>
  {!orders?<p>Carregando…</p>:orders.length===0?<p>Nenhum pedido.</p>:<ul>{orders.map(r=><li key={r.id}><button className="link" disabled={busy} onClick={()=>void act(()=>open(r.id),'Pedido carregado.')}>Nº {r.number}</button> · {r.order_status} · {r.payment_status} · {r.fulfillment_status}{r.dispute_status!=='NONE'?` · disputa ${r.dispute_status}`:''} · {money(r.total_cents)}{r.open_incidents>0&&<strong className="error"> · {r.open_incidents} pendência(s){r.refund_due_cents!=='0'?` · devolução devida ${money(r.refund_due_cents)}`:''}</strong>}{r.open_requests>0&&<strong> · {r.open_requests} solicitação(ões)</strong>}</li>)}</ul>}</section>
 {d&&<section aria-label={`Pedido ${d.number}`}><h2>Pedido nº {d.number}</h2><p>{d.order_status} · pagamento {d.payment_status} · entrega {d.fulfillment_status} · disputa {d.dispute_status} · {d.shipping.name} ({d.shipping.kind==='PICKUP'?'retirada':'entrega'})</p><p>Comprador: {d.buyer.name} · {d.buyer.email}</p>
  <ul>{d.items.map(i=><li key={i.variant_id}>{i.quantity} × {i.snapshot.name} ({i.snapshot.sku}) · {money(i.price_cents)}</li>)}</ul><p>Total {money(d.total_cents)}</p>
  {d.incidents.some(i=>i.status==='OPEN'&&FINANCIAL.includes(i.code))&&<div className="local" role="note"><strong>Ação financeira pendente.</strong> Mesmo com pagamento {d.payment_status}, há valor a devolver. No piloto: 1) localize a transação abaixo pelo ID externo; 2) execute a devolução no painel do Mercado Pago; 3) anote a referência; 4) clique em “Solicitar nova consulta”. Somente a confirmação do gateway encerra a pendência.</div>}
  <h3>Expedição</h3>{blocks.length>0&&d.order_status==='OPEN'&&<p className="error">Bloqueios: {blocks.join(' ')}</p>}{d.shipment&&<p>{d.shipment.kind==='PICKUP'?`Retirada${d.shipment.ready_at?' pronta':''}`:`Enviado por ${d.shipment.carrier} ${d.shipment.tracking_code||''}`}{d.shipment.delivered_at?` · entregue ${new Date(d.shipment.delivered_at).toLocaleString('pt-BR')}`:''}</p>}
  <div className="row">{d.fulfillment_status==='UNFULFILLED'&&d.order_status==='OPEN'&&<button disabled={busy||blocks.length>0} onClick={()=>void act(()=>api(o('process'),'POST'),'Separação iniciada.')}>Iniciar separação</button>}
   {d.fulfillment_status==='PROCESSING'&&d.shipping.kind!=='PICKUP'&&<form aria-label="Registrar envio" onSubmit={e=>{const b=fields(e);void act(()=>api(o('ship'),'POST',b),'Envio registrado.');}}><label>Transportadora<input name="carrier" required maxLength={80}/></label><label>Código de rastreio<input name="tracking" maxLength={80}/></label><button disabled={busy}>Registrar envio</button></form>}
   {d.fulfillment_status==='PROCESSING'&&d.shipping.kind==='PICKUP'&&!d.shipment&&<button disabled={busy} onClick={()=>void act(()=>api(o('pickup-ready'),'POST'),'Comprador avisado da retirada.')}>Marcar pronto para retirada</button>}
   {((d.fulfillment_status==='SHIPPED')||(d.shipment?.kind==='PICKUP'&&d.shipment.ready_at&&d.fulfillment_status==='PROCESSING'))&&<form aria-label="Confirmar entrega" onSubmit={e=>{const b=fields(e);void act(()=>api(o('deliver'),'POST',b),'Entrega registrada.');}}><label>{d.shipment?.kind==='PICKUP'?'Comprovação da retirada (documento conferido, quem retirou)':'Observação da entrega (opcional)'}<input name="proof" required={d.shipment?.kind==='PICKUP'} maxLength={300}/></label><button disabled={busy}>Confirmar entrega</button></form>}
   {['SHIPPED','DELIVERED'].includes(d.fulfillment_status)&&<form aria-label="Registrar devolução física" onSubmit={e=>{const b=fields(e);void act(()=>api(o('return'),'POST',b),'Devolução física registrada; estoque não foi reposto automaticamente.');}}><label>Conferência da devolução<input name="note" required maxLength={500}/></label><button disabled={busy}>Registrar devolução física</button></form>}</div>
  <h3>Incidentes</h3>{d.incidents.length===0?<p>Nenhum.</p>:<ul>{d.incidents.map(i=><li key={i.id}><strong>{i.code}</strong> · {i.status} · devido {money(i.due_cents)}{i.note&&<small>Anotação: {i.note}</small>}{owner&&i.status==='OPEN'&&!REVIEW.includes(i.code)&&<form aria-label={`Anotar ${i.code}`} onSubmit={e=>{const b=fields(e);void act(()=>api(`purchase/orders/${d.id}/incidents/${i.id}/note`,'POST',b),'Referência anotada. Ela não confirma devolução.');}}><label>Referência externa / anotação<input name="note" required maxLength={1000}/></label><button disabled={busy}>Anotar</button></form>}{owner&&i.status==='OPEN'&&REVIEW.includes(i.code)&&<form aria-label={`Concluir revisão ${i.code}`} onSubmit={e=>{const b=fields(e);void act(()=>api(o(`incidents/${i.id}/resolve`),'POST',b),'Revisão registrada.');}}><label>Conclusão da revisão<input name="note" required maxLength={1000}/></label><button disabled={busy}>Concluir revisão</button></form>}</li>)}</ul>}
  <div className="row"><button disabled={busy} onClick={()=>void act(()=>api(o('reconcile'),'POST'),'Nova consulta ao gateway agendada.')}>Solicitar nova consulta ao gateway</button>{owner&&d.incidents.some(i=>i.status==='OPEN'&&i.code==='PAID_WITHOUT_STOCK')&&<button disabled={busy} onClick={()=>void act(()=>api(`purchase/orders/${d.id}/reallocate`,'POST'),'Estoque realocado.')}>Realocar estoque</button>}{owner&&d.outbox_failures>0&&<button disabled={busy} onClick={()=>void act(()=>api(`purchase/orders/${d.id}/outbox/retry`,'POST'),'Eventos reenfileirados.')}>Reprocessar eventos com falha ({d.outbox_failures})</button>}</div>
  {owner&&d.order_status==='OPEN'&&d.fulfillment_status==='UNFULFILLED'&&<form aria-label="Cancelar pedido" onSubmit={e=>{const b=fields(e);void act(()=>api(`purchase/orders/${d.id}/cancel`,'POST',b),'Pedido cancelado.');}}><label>Motivo do cancelamento<input name="reason" required maxLength={500}/></label><button disabled={busy}>Cancelar pedido</button></form>}
  <h3>Pagamentos</h3><ul>{d.attempts.map(a=><li key={a.id}>Tentativa {a.method} · {a.status} · {a.provider}/{a.environment}</li>)}{d.transactions.map(t=><li key={t.id}>Recebimento {t.classification} · {money(t.received_cents)} · devolvido {money(t.refunded_cents)} · ID externo <code>{t.external_id}</code></li>)}</ul>
  {owner&&attempt?.provider==='SIMULATED'&&<form aria-label="Simular gateway" onSubmit={e=>{const b=fields(e);void act(()=>api(`purchase/attempts/${attempt.id}/simulate`,'POST',b),'Fato simulado registrado; aguardando conciliação.');}}><label>Evento do provedor SIMULADO<select name="status"><option value="APPROVED">Aprovar</option><option value="REJECTED">Rejeitar</option><option value="REFUNDED">Devolução</option><option value="DISPUTED">Abrir disputa</option><option value="DISPUTE_WON">Disputa vencida</option><option value="DISPUTE_LOST">Disputa perdida</option></select></label><label>Valor da devolução em centavos<input name="amount_cents" pattern="[0-9]*" defaultValue={d.total_cents}/></label><button disabled={busy}>Enviar evento simulado</button></form>}
  <h3>Notificações ao comprador</h3>{notes.length===0?<p>Nenhuma.</p>:<ul>{notes.map(n=><li key={n.id}>{n.template} · {n.status}{n.status==='SIMULATED'?' (provedor local, sem envio externo)':''} · tentativas {n.attempts}{n.last_error?` · ${n.last_error}`:''}{owner&&['FAILED','HELD'].includes(n.status)&&<button disabled={busy} onClick={()=>void act(()=>api(`operations/notifications/${n.id}/retry`,'POST'),'Reenvio agendado.')}>Reenviar</button>}</li>)}</ul>}
  <h3>Documento fiscal externo</h3><form aria-label="Registrar documento fiscal" onSubmit={e=>{const b=fields(e);void act(()=>api(o('fiscal'),'POST',b),'Referência fiscal registrada.');}}><label>Referência (ex.: chave da NF-e emitida fora da plataforma)<input name="reference" required maxLength={120} defaultValue={d.fiscal_reference||''}/></label><button disabled={busy}>Salvar referência</button></form>
  {owner&&<><h3>Correção auditada de endereço</h3><form aria-label="Corrigir endereço" onSubmit={e=>{const b=fields(e),reason=b.reason;delete b.reason;void act(()=>api(`purchase/orders/${d.id}/address`,'POST',{address:b,reason}),'Correção registrada; original preservado.');}}>{['cep','street','number','city','state','complement'].map(k=><label key={k}>{k}<input name={k} required={k!=='complement'}/></label>)}<label>Motivo<input name="reason" required maxLength={500}/></label><button disabled={busy}>Registrar correção</button></form>
   <h3>Privacidade do comprador</h3><div className="row"><button disabled={busy} onClick={()=>void act(()=>download('CONSUMER',d.id),'Exportação gerada (link de 15 min, já consumido).')}>Exportar dados do comprador</button><button disabled={busy} onClick={()=>void act(()=>api(o('access/revoke'),'POST'),'Links de acompanhamento revogados.')}>Revogar links de acompanhamento</button></div>
   <form aria-label="Anonimizar comprador" onSubmit={e=>{const b=fields(e);if(confirm('Anonimizar dados pessoais deste pedido? Fatos financeiros são preservados.'))void act(()=>api(o('erase'),'POST',b),'Dados pessoais anonimizados.');else e.preventDefault();}}><label>Motivo da eliminação (protocolo do titular)<input name="reason" required maxLength={500}/></label><button disabled={busy}>Anonimizar dados pessoais</button></form></>}
  <h3>Protocolos do consumidor</h3><ul>{d.protocols.map(p=><li key={p.id}><a href={`/painel/${tenantId}/atendimento#${p.id}`}>{p.kind} · {p.status} · {new Date(p.created_at).toLocaleString('pt-BR')}</a></li>)}</ul>
  <h3>Histórico</h3><ul>{d.history.map((h,i)=><li key={i}>{new Date(h.created_at).toLocaleString('pt-BR')} · {h.event} · {h.reason}</li>)}</ul></section>}
 </main>;
}
