import { sql } from 'drizzle-orm';
import { customType, pgSchema, uuid, text, timestamp, unique, foreignKey, bigint, integer, boolean, jsonb } from 'drizzle-orm/pg-core';
const access = pgSchema('access');
const shop = pgSchema('shop');
const dates = () => ({ createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() });
export const users = access.table('users', {
  id: uuid('id').primaryKey(), email: text('email').notNull().unique(), passwordHash: text('password_hash').notNull(),
  verifiedAt: timestamp('verified_at', { withTimezone: true }), ...dates()
});
export const sessions = access.table('sessions', {
  id: uuid('id').primaryKey(), userId: uuid('user_id').notNull().references(() => users.id), tokenHash: text('token_hash').notNull().unique(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), revokedAt: timestamp('revoked_at', { withTimezone: true }), ...dates()
});
export const accessTokens = access.table('tokens', {
  id: uuid('id').primaryKey(), userId: uuid('user_id').notNull().references(() => users.id), kind: text('kind').notNull(), tokenHash: text('token_hash').notNull().unique(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), consumedAt: timestamp('consumed_at', { withTimezone: true }), ...dates()
});
export const tenants = shop.table('tenants', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull(), slug: text('slug').notNull().unique(), name: text('name').notNull(),
  lifecycleStatus: text('lifecycle_status').notNull().default('DRAFT'), timezone: text('timezone').notNull().default('America/Sao_Paulo'), ...dates()
}, t => [unique().on(t.tenantId, t.id)]);
export const memberships = shop.table('tenant_memberships', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id), userId: uuid('user_id').notNull().references(() => users.id),
  role: text('role').notNull(), status: text('status').notNull().default('ACTIVE'), ...dates()
}, t => [unique().on(t.tenantId, t.id), unique().on(t.tenantId, t.userId)]);
export const settings = shop.table('store_settings', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().unique().references(() => tenants.id), displayName: text('display_name').notNull(),
  timezone: text('timezone').notNull().default('America/Sao_Paulo'), updatedByMembershipId: uuid('updated_by_membership_id').notNull(), ...dates()
}, t => [unique().on(t.tenantId, t.id), foreignKey({columns: [t.tenantId, t.updatedByMembershipId], foreignColumns: [memberships.tenantId, memberships.id]})]);
export const invitations = shop.table('invitations', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id), email: text('email').notNull(), role: text('role').notNull().default('EMPLOYEE'),
  tokenHash: text('token_hash').notNull().unique(), inviterMembershipId: uuid('inviter_membership_id').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), consumedAt: timestamp('consumed_at', { withTimezone: true }), ...dates()
}, t => [unique().on(t.tenantId, t.id), foreignKey({columns: [t.tenantId, t.inviterMembershipId], foreignColumns: [memberships.tenantId, memberships.id]})]);

const identity=()=>({id:uuid('id').primaryKey(),tenantId:uuid('tenant_id').notNull().references(()=>tenants.id)});
const created=()=>timestamp('created_at',{withTimezone:true}).notNull().defaultNow();
const money=(name:string)=>bigint(name,{mode:'bigint'}).notNull();
export const categories=shop.table('categories',{...identity(),name:text('name').notNull(),slug:text('slug').notNull(),createdAt:created()},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId,t.slug)]);
export const products=shop.table('products',{...identity(),categoryId:uuid('category_id'),name:text('name').notNull(),slug:text('slug').notNull(),description:text('description').notNull().default(''),status:text('status').notNull().default('DRAFT'),searchDocument:customType<{data:string}>({dataType:()=> 'tsvector'})('search_document').generatedAlwaysAs(sql`shop.product_search(name||' '||description)`),...dates()},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId,t.slug),foreignKey({columns:[t.tenantId,t.categoryId],foreignColumns:[categories.tenantId,categories.id]})]);
export const productSlugs=shop.table('product_slugs',{...identity(),productId:uuid('product_id').notNull(),slug:text('slug').notNull()},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId,t.slug),foreignKey({columns:[t.tenantId,t.productId],foreignColumns:[products.tenantId,products.id]})]);
export const productVariants=shop.table('product_variants',{...identity(),productId:uuid('product_id').notNull(),sku:text('sku').notNull(),combinationKey:text('combination_key').notNull(),isDefault:boolean('is_default').notNull().default(false),active:boolean('active').notNull().default(true),priceCents:money('price_cents'),weightG:integer('weight_g').notNull().default(0),widthMm:integer('width_mm').notNull().default(0),heightMm:integer('height_mm').notNull().default(0),lengthMm:integer('length_mm').notNull().default(0)},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId,t.sku),unique().on(t.tenantId,t.productId,t.id),unique().on(t.tenantId,t.productId,t.combinationKey),foreignKey({columns:[t.tenantId,t.productId],foreignColumns:[products.tenantId,products.id]})]);
export const productOptions=shop.table('product_options',{...identity(),productId:uuid('product_id').notNull(),name:text('name').notNull(),createdAt:created()},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId,t.productId,t.id),unique().on(t.tenantId,t.productId,t.name),foreignKey({columns:[t.tenantId,t.productId],foreignColumns:[products.tenantId,products.id]})]);
export const optionValues=shop.table('option_values',{...identity(),productId:uuid('product_id').notNull(),optionId:uuid('option_id').notNull(),value:text('value').notNull(),createdAt:created()},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId,t.productId,t.optionId,t.id),unique().on(t.tenantId,t.optionId,t.value),foreignKey({columns:[t.tenantId,t.productId,t.optionId],foreignColumns:[productOptions.tenantId,productOptions.productId,productOptions.id]})]);
export const variantValues=shop.table('variant_values',{...identity(),productId:uuid('product_id').notNull(),variantId:uuid('variant_id').notNull(),optionId:uuid('option_id').notNull(),valueId:uuid('value_id').notNull(),createdAt:created()},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId,t.variantId,t.optionId),foreignKey({columns:[t.tenantId,t.productId,t.variantId],foreignColumns:[productVariants.tenantId,productVariants.productId,productVariants.id]}),foreignKey({columns:[t.tenantId,t.productId,t.optionId,t.valueId],foreignColumns:[optionValues.tenantId,optionValues.productId,optionValues.optionId,optionValues.id]})]);
export const inventoryLocations=shop.table('inventory_locations',{...identity(),name:text('name').notNull()},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId,t.name)]);
export const inventoryItems=shop.table('inventory_items',{...identity(),variantId:uuid('variant_id').notNull(),locationId:uuid('location_id').notNull(),onHand:integer('on_hand').notNull().default(0),reserved:integer('reserved').notNull().default(0)},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId,t.variantId,t.locationId),foreignKey({columns:[t.tenantId,t.variantId],foreignColumns:[productVariants.tenantId,productVariants.id]}),foreignKey({columns:[t.tenantId,t.locationId],foreignColumns:[inventoryLocations.tenantId,inventoryLocations.id]})]);
export const inventoryMovements=shop.table('inventory_movements',{...identity(),itemId:uuid('item_id').notNull(),actorMembershipId:uuid('actor_membership_id').notNull(),delta:integer('delta').notNull(),balance:integer('balance').notNull(),reason:text('reason').notNull(),createdAt:created()},t=>[unique().on(t.tenantId,t.id),foreignKey({columns:[t.tenantId,t.itemId],foreignColumns:[inventoryItems.tenantId,inventoryItems.id]}),foreignKey({columns:[t.tenantId,t.actorMembershipId],foreignColumns:[memberships.tenantId,memberships.id]})]);
export const mediaAssets=shop.table('media_assets',{...identity(),actorMembershipId:uuid('actor_membership_id').notNull(),status:text('status').notNull(),originalKey:text('original_key').notNull(),contentHash:text('content_hash').notNull(),originalBytes:money('original_bytes').default(0n),storedBytes:money('stored_bytes').default(0n),renditions:jsonb('renditions').$type<{key:string;width:number;height:number;bytes:number}[]>().notNull().default([]),...dates()},t=>[unique().on(t.tenantId,t.id),foreignKey({columns:[t.tenantId,t.actorMembershipId],foreignColumns:[memberships.tenantId,memberships.id]})]);
export const productMedia=shop.table('product_media',{...identity(),productId:uuid('product_id').notNull(),assetId:uuid('asset_id').notNull()},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId,t.productId,t.assetId),foreignKey({columns:[t.tenantId,t.productId],foreignColumns:[products.tenantId,products.id]}),foreignKey({columns:[t.tenantId,t.assetId],foreignColumns:[mediaAssets.tenantId,mediaAssets.id]})]);
export const merchantProfiles=shop.table('merchant_profiles',{...identity(),profile:jsonb('profile').$type<Record<string,unknown>>().notNull(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId)]);
export const themeRevisions=shop.table('theme_revisions',{...identity(),schemaVersion:integer('schema_version').notNull(),content:jsonb('content').$type<Record<string,unknown>>().notNull(),createdAt:created()},t=>[unique().on(t.tenantId,t.id)]);
export const themeMedia=shop.table('theme_media',{...identity(),revisionId:uuid('revision_id').notNull(),assetId:uuid('asset_id').notNull()},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId,t.revisionId,t.assetId),foreignKey({columns:[t.tenantId,t.revisionId],foreignColumns:[themeRevisions.tenantId,themeRevisions.id]}),foreignKey({columns:[t.tenantId,t.assetId],foreignColumns:[mediaAssets.tenantId,mediaAssets.id]})]);
export const storefronts=shop.table('storefronts',{...identity(),draftRevisionId:uuid('draft_revision_id'),publishedRevisionId:uuid('published_revision_id'),version:money('version').default(0n)},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId),foreignKey({columns:[t.tenantId,t.draftRevisionId],foreignColumns:[themeRevisions.tenantId,themeRevisions.id]}),foreignKey({columns:[t.tenantId,t.publishedRevisionId],foreignColumns:[themeRevisions.tenantId,themeRevisions.id]})]);
export const platformRoutes=shop.table('platform_routes',{...identity(),hostname:text('hostname').notNull().unique(),slug:text('slug').notNull().unique(),canonical:text('canonical').notNull()},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId)]);
export const storefrontEvents=shop.table('storefront_events',{...identity(),version:money('version'),operation:text('operation').notNull(),createdAt:created()},t=>[unique().on(t.tenantId,t.id)]);
export const carts=shop.table('carts',{...identity(),tokenHash:text('token_hash').notNull(),version:money('version').default(0n),expiresAt:timestamp('expires_at',{withTimezone:true}).notNull(),createdAt:created()},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId,t.tokenHash)]);
export const cartItems=shop.table('cart_items',{...identity(),cartId:uuid('cart_id').notNull(),variantId:uuid('variant_id').notNull(),quantity:integer('quantity').notNull()},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId,t.cartId,t.variantId),foreignKey({columns:[t.tenantId,t.cartId],foreignColumns:[carts.tenantId,carts.id]}),foreignKey({columns:[t.tenantId,t.variantId],foreignColumns:[productVariants.tenantId,productVariants.id]})]);
export const shippingRules=shop.table('shipping_rules',{...identity(),name:text('name').notNull(),kind:text('kind').notNull(),cepStart:text('cep_start').notNull(),cepEnd:text('cep_end').notNull(),priceCents:money('price_cents'),days:integer('days').notNull(),priority:integer('priority').notNull(),version:money('version').default(1n),active:boolean('active').notNull().default(true)},t=>[unique().on(t.tenantId,t.id)]);
export const shippingQuotes=shop.table('shipping_quotes',{...identity(),cartId:uuid('cart_id').notNull(),ruleId:uuid('rule_id').notNull(),fingerprint:text('fingerprint').notNull(),address:jsonb('address').$type<Record<string,string>>().notNull(),priceCents:money('price_cents'),expiresAt:timestamp('expires_at',{withTimezone:true}).notNull(),createdAt:created()},t=>[unique().on(t.tenantId,t.id),foreignKey({columns:[t.tenantId,t.cartId],foreignColumns:[carts.tenantId,carts.id]}),foreignKey({columns:[t.tenantId,t.ruleId],foreignColumns:[shippingRules.tenantId,shippingRules.id]})]);
export const mediaUsage=shop.table('media_usage',{...identity(),storedBytes:money('stored_bytes').default(0n),reconciledAt:timestamp('reconciled_at',{withTimezone:true})},t=>[unique().on(t.tenantId,t.id),unique().on(t.tenantId)]);
